In [1]:
#Importing all necessary modules
import numpy as np
import sympy as sym
import math
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

In [2]:
#Constants
Tol = 1.0E-8; #Tolerance
mu_S = 1.32712440042E20; #m^3/s^2
mu_day = 2.22972472E-24;
mu_S = mu_S*mu_day; #AU^3/day^2
dt = 1600;
Iter_1I = 0;
Iter_2I = 0;
Iter_E = 0;
Iter_1I_pg = 0;
Iter_2I_pg = 0;
Iter_E_pg = 0;
Iter_1I_rg = 0;
Iter_2I_rg = 0;
Iter_E_rg = 0;
z_1I_pg = 0.0;
z_2I_pg = z_1I_pg;
z_E_pg = z_1I_pg;
z_1I_rg = z_1I_pg;
z_2I_rg = z_1I_rg;
z_E_rg = z_1I_rg;
print(mu_S)
print(dt)

0.00029591220821316525
1600


In [3]:
#Problem 5
#Initial vectors (AU and AU/day)
r_1I = np.array([3.515868886595499E-2,-3.162046390773074,4.493983111703389]);
v_1I = np.array([-2.317577766980901E-3,9.843360903693031E-3,-1.541856855538041E-2]);
r_2I = np.array([7.249472033259724,14.61063037906177,14.24274452216359]);
v_2I = np.array([-8.241709369476881E-3,-1.156219024581502E-2,-1.317135977481448E-2]);
r_E = np.array([-1.796136509111975E-1,9.667949206859814E-1,-3.668681017942158E-5]);
v_E = np.array([-1.720038360888334E-2,-3.211186197806460E-3,7.927736735960840E-7]);
print(r_1I)
print(v_1I)
print(r_2I)
print(v_2I)
print(r_E)
print(v_E)

[ 0.03515869 -3.16204639  4.49398311]
[-0.00231758  0.00984336 -0.01541857]
[ 7.24947203 14.61063038 14.24274452]
[-0.00824171 -0.01156219 -0.01317136]
[-1.79613651e-01  9.66794921e-01 -3.66868102e-05]
[-1.72003836e-02 -3.21118620e-03  7.92773674e-07]


In [4]:
#Initial Magnitudes (AU and AU/day)
r_1IM = np.sqrt(np.dot(r_1I,r_1I));
v_1IM = np.sqrt(np.dot(v_1I,v_1I));
r_2IM = np.sqrt(np.dot(r_2I,r_2I));
v_2IM = np.sqrt(np.dot(v_2I,v_2I));
r_EM = np.sqrt(np.dot(r_E,r_E));
v_EM = np.sqrt(np.dot(v_E,v_E));
print(r_1IM)
print(v_1IM)
print(r_2IM)
print(v_2IM)
print(r_EM)
print(v_EM)

5.495057571953097
0.018438958129008327
21.653663347299887
0.01936736262192
0.9833379295053073
0.017497568794498722


In [5]:
#Radial component velocities (AU/day)
nu_r_1I = (np.dot(r_1I,v_1I))/r_1IM;
nu_r_2I = (np.dot(r_2I,v_2I))/r_2IM;
nu_r_E = (np.dot(r_E,v_E))/r_EM;
print(nu_r_1I)
print(nu_r_2I)
print(nu_r_E)

-0.01828869528532203
-0.019224240962828414
-1.539128816429416e-05


In [6]:
#Specific angular momentums (AU^2/day)
h_1I = np.cross(r_1I,v_1I);
h_2I = np.cross(r_2I,v_2I);
h_E = np.cross(r_E,v_E);
print(h_1I)
print(h_2I)
print(h_E)

[ 0.00451833 -0.00987306 -0.00698221]
[-0.02776455 -0.02189916  0.03659679]
[6.48641382e-07 7.73420182e-07 1.72060164e-02]


In [7]:
#Specific angular momentum magnitudes (AU^2/day)
h_1IM = np.sqrt(np.dot(h_1I,h_1I));
h_2IM = np.sqrt(np.dot(h_2I,h_2I));
h_EM = np.sqrt(np.dot(h_E,h_E));
print(h_1IM)
print(h_2IM)
print(h_EM)

0.012909060595588018
0.050889768351352296
0.017206016413271734


In [8]:
#Inclinations (Rad)
i_1I = np.arccos(h_1I[2]/h_1IM);
i_2I = np.arccos(h_2I[2]/h_2IM);
i_E = np.arccos(h_E[2]/h_EM);
print(i_1I)
print(i_2I)
print(i_E)

2.1422752865992707
0.7682345319822067
5.866627661176234e-05


In [9]:
#Node line (AU^2/day)
K_vector = np.array([0,0,1]);
N_1I = np.cross(K_vector,h_1I);
N_2I = np.cross(K_vector,h_2I);
N_E = np.cross(K_vector,h_E);
print(N_1I)
print(N_2I)
print(N_E)

[ 0.00987306  0.00451833 -0.        ]
[ 0.02189916 -0.02776455  0.        ]
[-7.73420182e-07  6.48641382e-07  0.00000000e+00]


In [10]:
#Node line magnitudes
N_1IM = np.sqrt(np.dot(N_1I,N_1I));
N_2IM = np.sqrt(np.dot(N_2I,N_2I));
N_EM = np.sqrt(np.dot(N_E,N_E));
print(N_1IM)
print(N_2IM)
print(N_EM)

0.010857836176322253
0.0353616057072317
1.0094129092683798e-06


In [11]:
#Right ascensions
if N_1I[1] >= 0:
    RA_1I = np.arccos(N_1I[0]/N_1IM);
else:
    RA_1I_pg = np.pi - np.arccos(N_1I[0]/N_1IM);
if N_2I[1] >= 0:
    RA_2I = np.arccos(N_2I[0]/N_2IM);
else:
    RA_2I = np.pi - np.arccos(N_2I[0]/N_2IM);
if N_E[1] >= 0:
    RA_E = np.arccos(N_E[0]/N_EM);
else:
    RA_E = np.pi - np.arccos(N_E[0]/N_EM);
print(RA_1I)
print(RA_2I)
print(RA_E)

0.42919123642669793
2.2386368793087956
2.443715341975923


In [12]:
#Eccentricities
e_1I = (1/mu_S)*(np.cross(v_1I,h_1I) - mu_S*(r_1I/r_1IM));
e_2I = (1/mu_S)*(np.cross(v_2I,h_2I) - mu_S*(r_2I/r_2IM));
e_E = (1/mu_S)*(np.cross(v_E,h_E) - mu_S*(r_E/r_EM));
print(e_1I)
print(e_2I)
print(e_E)

[-0.75309549  0.2853215  -0.89079705]
[-2.73949425  1.5803764  -1.13266499]
[-4.05950884e-03  1.69513125e-02 -6.08933614e-07]


In [13]:
#Eccentricity magnitudes
e_1IM = np.sqrt(np.dot(e_1I,e_1I));
e_2IM = np.sqrt(np.dot(e_2I,e_2I));
e_EM = np.sqrt(np.dot(e_E,e_E));
print(e_1IM)
print(e_2IM)
print(e_EM)

1.2008665883995984
3.3593672502599703
0.017430622659287243


In [14]:
#Arguments of perigee numerators and denominators
omega_1I_n = np.dot(N_1I,e_1I);
omega_1I_d = N_1IM*e_1IM;
omega_2I_n = np.dot(N_2I,e_2I);
omega_2I_d = N_2IM*e_2IM;
omega_E_n = np.dot(N_E,e_E);
omega_E_d = N_EM*e_EM;
print(omega_1I_n)
print(omega_1I_d)
print(omega_2I_n)
print(omega_2I_d)
print(omega_E_n)
print(omega_E_d)

-0.006146178874600533
0.013038812686461844
-0.10387104942424198
0.11879262012948023
1.413502880779726e-08
1.759469552887048e-08


In [15]:
#Arguments of perigee
if e_1I[1] >= 0:
    omega_1I = np.arccos(omega_1I_n/omega_1I_d);
else:
    omega_1I = np.pi - np.arccos(omega_1I_n/omega_1I_d);
if e_2I[1] >= 0:
    omega_2I = np.arccos(omega_2I_n/omega_2I_d);
else:
    omega_2I = np.pi - np.arccos(omega_2I_n/omega_2I_d);
if e_E[1] >= 0:
    omega_E = np.arccos(omega_E_n/omega_E_d);
else:
    omega_E = np.pi - np.arccos(omega_E_n/omega_E_d);
print(omega_1I)
print(omega_2I)
print(omega_E)

2.061646274996333
2.6349730487680314
0.6378652966895136


In [16]:
#True anomalies numerators and denominators
theta_1I_n = np.dot(e_1I,r_1I);
theta_1I_d = e_1IM*r_1IM;
theta_2I_n = np.dot(e_2I,r_2I);
theta_2I_d = e_2IM*r_2IM;
theta_E_n = np.dot(e_E,r_E);
theta_E_d = e_1IM*r_1IM;
print(theta_1I_n)
print(theta_1I_d)
print(theta_2I_n)
print(theta_2I_d)
print(theta_E_n)
print(theta_E_d)

-4.931904579831467
6.598831039490697
-12.90184963034531
72.74260749707392
0.01711758600527277
6.598831039490697


In [17]:
#True anomalies
if nu_r_1I >= 0:
    theta_1I = np.arccos(theta_1I_n/theta_1I_d);
else:
    theta_1I = np.pi - np.arccos(theta_1I_n/theta_1I_d);
if nu_r_2I >= 0:
    theta_2I = np.arccos(theta_2I_n/theta_2I_d);
else:
    theta_2I = np.pi - np.arccos(theta_2I_n/theta_2I_d);
if nu_r_E >= 0:
    theta_E = np.arccos(theta_E_n/theta_E_d);
else:
    theta_E = np.pi - np.arccos(theta_E_n/theta_E_d);
print(theta_1I)
print(theta_2I)
print(theta_E)

0.726670449454442
1.3924899724350381
1.5733903627840415


In [18]:
#Semi-major axis
a_1I = 1/((2/r_1IM) - (nu_r_1I**2 / mu_S));
a_2I = 1/((2/r_2IM) - (nu_r_2I**2 / mu_S));
a_E = 1/((2/r_EM) - (nu_r_E**2 / mu_S));
print(a_1I)
print(a_2I)
print(a_E)

-1.304870503737988
-0.8646334514626245
0.49166915827575614
