In [1]:
#Importing all necessary modules
import numpy as np
import sympy as sym
import math
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

In [2]:
#Constants
Tol = 1.0E-8; #Tolerance
mu_S = 1.32712440042E20; #m^3/s^2
mu_day = 2.22972472E-24;
mu_S = mu_S*mu_day; #AU^3/day^2
dt_initial = 600;
dt_final = 1600;
dt = dt_final - dt_initial;
Iter_initial_1I = 0;
Iter_initial_2I = 0;
Iter_initial_E = 0;
Iter_final_1I = 0;
Iter_final_2I = 0;
Iter_final_E = 0;
Iter_1I_pg = 0;
Iter_2I_pg = 0;
Iter_E_pg = 0;
Iter_1I_rg = 0;
Iter_2I_rg = 0;
Iter_E_rg = 0;
Z_1I_pg = 1.5;
Z_2I_pg = Z_1I_pg;
Z_E_pg = Z_1I_pg;
Z_1I_rg = Z_1I_pg;
Z_2I_rg = Z_1I_rg;
Z_E_rg = Z_1I_rg;
print(mu_S)
print(dt)

0.00029591220821316525
1000


In [3]:
#Problem 1
#Initial vectors (AU and AU/day)
r_1I = np.array([3.515868886595499E-2,-3.162046390773074,4.493983111703389]);
v_1I = np.array([-2.317577766980901E-3,9.843360903693031E-3,-1.541856855538041E-2]);
r_2I = np.array([7.249472033259724,14.61063037906177,14.24274452216359]);
v_2I = np.array([-8.241709369476881E-3,-1.156219024581502E-2,-1.317135977481448E-2]);
r_E = np.array([-1.796136509111975E-1,9.667949206859814E-1,-3.668681017942158E-5]);
v_E = np.array([-1.720038360888334E-2,-3.211186197806460E-3,7.927736735960840E-7]);
print(r_1I)
print(v_1I)
print(r_2I)
print(v_2I)
print(r_E)
print(v_E)

[ 0.03515869 -3.16204639  4.49398311]
[-0.00231758  0.00984336 -0.01541857]
[ 7.24947203 14.61063038 14.24274452]
[-0.00824171 -0.01156219 -0.01317136]
[-1.79613651e-01  9.66794921e-01 -3.66868102e-05]
[-1.72003836e-02 -3.21118620e-03  7.92773674e-07]


In [4]:
#Initial Magnitudes (AU and AU/day)
r_1IM = np.sqrt(np.dot(r_1I,r_1I));
v_1IM = np.sqrt(np.dot(v_1I,v_1I));
r_2IM = np.sqrt(np.dot(r_2I,r_2I));
v_2IM = np.sqrt(np.dot(v_2I,v_2I));
r_EM = np.sqrt(np.dot(r_E,r_E));
v_EM = np.sqrt(np.dot(v_E,v_E));
print(r_1IM)
print(v_1IM)
print(r_2IM)
print(v_2IM)
print(r_EM)
print(v_EM)

5.495057571953097
0.018438958129008327
21.653663347299887
0.01936736262192
0.9833379295053073
0.017497568794498722


In [5]:
#Radial component velocities (AU/day)
nu_r_1I = (np.dot(r_1I,v_1I))/r_1IM;
nu_r_2I = (np.dot(r_2I,v_2I))/r_2IM;
nu_r_E = (np.dot(r_E,v_E))/r_EM;
print(nu_r_1I)
print(nu_r_2I)
print(nu_r_E)

-0.01828869528532203
-0.019224240962828414
-1.539128816429416e-05


In [6]:
#Alpha (Semi-major axis reciprocal, 1/AU) and Semi-major axis (AU)
alpha_1I = (2/r_1IM) - (v_1IM**2 / mu_S);
alpha_2I = (2/r_2IM) - (v_2IM**2 / mu_S);
alpha_E = (2/r_EM) - (v_EM**2 / mu_S);
print(alpha_1I)
print(alpha_2I)
print(alpha_E)

-0.785009703080843
-1.1752247768018413
0.9992410036177539


In [7]:
#Initial Universal Variable (AU^1/2)
Chi_initial_1I = np.sqrt(mu_S)*np.abs(alpha_1I)*dt_initial;
Chi_initial_2I = np.sqrt(mu_S)*np.abs(alpha_2I)*dt_initial;
Chi_initial_E = np.sqrt(mu_S)*np.abs(alpha_E)*dt_initial;
print(Chi_initial_1I)
print(Chi_initial_2I)
print(Chi_initial_E)

8.102288752472534
12.129799737937752
10.31342557021582


In [8]:
#Final Universal Variable (AU^1/2)
Chi_final_1I = np.sqrt(mu_S)*np.abs(alpha_1I)*dt_final;
Chi_final_2I = np.sqrt(mu_S)*np.abs(alpha_2I)*dt_final;
Chi_final_E = np.sqrt(mu_S)*np.abs(alpha_E)*dt_final;
print(Chi_final_1I)
print(Chi_final_2I)
print(Chi_final_E)

21.606103339926754
32.34613263450068
27.502468187242187


In [9]:
#Initial z terms
z_initial_1I = alpha_1I*Chi_initial_1I**2;
z_initial_2I = alpha_2I*Chi_initial_2I**2;
z_initial_E = alpha_E*Chi_initial_E**2;
print(z_initial_1I)
print(z_initial_2I)
print(z_initial_E)

-51.533597156281424
-172.91322084668562
106.286015016223


In [10]:
#Final z terms
z_final_1I = alpha_1I*Chi_final_1I**2;
z_final_2I = alpha_2I*Chi_final_2I**2;
z_final_E = alpha_E*Chi_final_E**2;
print(z_final_1I)
print(z_final_2I)
print(z_final_E)

-366.46113533355674
-1229.6051260208758
755.8116623375859


In [11]:
#Initial C functions
C_initial_1I = (np.cosh(np.sqrt(-z_initial_1I)) - 1)/-z_initial_1I;
C_initial_2I = (np.cosh(np.sqrt(-z_initial_2I)) - 1)/-z_initial_2I;
C_initial_E = (1 - np.cos(np.sqrt(z_initial_E)))/z_initial_E;
print(C_initial_1I)
print(C_initial_2I)
print(C_initial_E)

12.70230444148628
1485.7964654091058
0.015368872003262271


In [12]:
#Final C functions
C_final_1I = (np.cosh(np.sqrt(-z_final_1I)) - 1)/-z_final_1I;
C_final_2I = (np.cosh(np.sqrt(-z_final_2I)) - 1)/-z_final_2I;
C_final_E = (1 - np.cos(np.sqrt(z_final_E)))/z_final_E;
print(C_final_1I)
print(C_final_2I)
print(C_final_E)

281007.0333484178
688740400927.8279
0.0022615299666585583


In [13]:
#Initial S functions
S_initial_1I = (np.sinh(np.sqrt(-z_initial_1I)) - np.sqrt(-z_initial_1I))/(np.sqrt(-z_initial_1I)**3);
S_initial_2I = (np.sinh(np.sqrt(-z_initial_2I)) - np.sqrt(-z_initial_2I))/(np.sqrt(-z_initial_2I)**3);
S_initial_E = (np.sqrt(z_initial_E) - np.sin(np.sqrt(z_initial_E)))/(np.sqrt(z_initial_E)**3);
print(S_initial_1I)
print(S_initial_2I)
print(S_initial_E)

1.7527421335961526
112.98601256145113
0.01011470467398887


In [14]:
#Final S functions
S_final_1I = (np.sinh(np.sqrt(-z_final_1I)) - np.sqrt(-z_final_1I))/(np.sqrt(-z_final_1I)**3);
S_final_2I = (np.sinh(np.sqrt(-z_final_2I)) - np.sqrt(-z_final_2I))/(np.sqrt(-z_final_2I)**3);
S_final_E = (np.sqrt(z_final_E) - np.sin(np.sqrt(z_final_E)))/(np.sqrt(z_final_E)**3);
print(S_final_1I)
print(S_final_2I)
print(S_final_E)

14679.225839495928
19641412951.691013
0.001289156154631272


In [15]:
#f initial (AU^1/2)
f_initial_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*(Chi_initial_1I**2)*(C_initial_1I) + (1 - alpha_1I*r_1IM)*(Chi_initial_1I**3)*(S_initial_1I) + (r_1IM*Chi_initial_1I) - np.sqrt(mu_S)*dt_initial;
f_initial_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*(Chi_initial_2I**2)*(C_initial_2I) + (1 - alpha_2I*r_2IM)*(Chi_initial_2I**3)*(S_initial_2I) + (r_2IM*Chi_initial_2I) - np.sqrt(mu_S)*dt_initial;
f_initial_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*(Chi_initial_E**2)*(C_initial_E) + (1 - alpha_E*r_EM)*(Chi_initial_E**3)*(S_initial_E) + (r_EM*Chi_initial_E) - np.sqrt(mu_S)*dt_initial;
print(f_initial_1I)
print(f_initial_2I)
print(f_initial_E)

116.37520436850168
43197.94501610339
0.01204676002369176


In [16]:
#f final (AU^1/2)
f_final_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*(Chi_final_1I**2)*(C_final_1I) + (1 - alpha_1I*r_1IM)*(Chi_final_1I**3)*(S_final_1I) + (r_1IM*Chi_final_1I) - np.sqrt(mu_S)*dt_final;
f_final_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*(Chi_final_2I**2)*(C_final_2I) + (1 - alpha_2I*r_2IM)*(Chi_final_2I**3)*(S_final_2I) + (r_2IM*Chi_final_2I) - np.sqrt(mu_S)*dt_final;
f_final_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*(Chi_final_E**2)*(C_final_E) + (1 - alpha_E*r_EM)*(Chi_final_E**3)*(S_final_E) + (r_EM*Chi_final_E) - np.sqrt(mu_S)*dt_final;
print(f_final_1I)
print(f_final_2I)
print(f_final_E)

20354050.09231681
142395287789182.88
-0.013790478720107302


In [17]:
#fprime initial (AU^2/3)
fprime_initial_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*Chi_initial_1I*(1 - alpha_1I*(Chi_initial_1I**2)*S_initial_1I) + (1 - alpha_1I*r_1IM)*(Chi_initial_1I**2)*C_initial_1I + r_1IM;
fprime_initial_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*Chi_initial_2I*(1 - alpha_2I*(Chi_initial_2I**2)*S_initial_2I) + (1 - alpha_2I*r_2IM)*(Chi_initial_2I**2)*C_initial_2I + r_2IM;
fprime_initial_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*Chi_initial_E*(1 - alpha_E*(Chi_initial_E**2)*S_initial_E) + (1 - alpha_E*r_EM)*(Chi_initial_E**2)*C_initial_E + r_EM;
print(fprime_initial_1I)
print(fprime_initial_2I)
print(fprime_initial_E)

113.54128018761274
46829.14019421005
1.0124771365481888


In [18]:
#fprime final (AU^2/3)
fprime_final_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*Chi_final_1I*(1 - alpha_1I*(Chi_final_1I**2)*S_final_1I) + (1 - alpha_1I*r_1IM)*(Chi_final_1I**2)*C_final_1I + r_1IM;
fprime_final_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*Chi_final_2I*(1 - alpha_2I*(Chi_final_2I**2)*S_final_2I) + (1 - alpha_2I*r_2IM)*(Chi_final_2I**2)*C_final_2I + r_2IM;
fprime_final_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*Chi_final_E*(1 - alpha_E*(Chi_final_E**2)*S_final_E) + (1 - alpha_E*r_EM)*(Chi_final_E**2)*C_final_E + r_EM;
print(fprime_final_1I)
print(fprime_final_2I)
print(fprime_final_E)

18033886.685471404
154367576907401.66
1.0124961446270202


In [19]:
#Ratio initial
Ratio_initial_1I = f_initial_1I/fprime_initial_1I;
Ratio_initial_2I = f_initial_2I/fprime_initial_2I;
Ratio_initial_E = f_initial_E/fprime_initial_E;
print(Ratio_initial_1I)
print(Ratio_initial_2I)
print(Ratio_initial_E)

1.0249594171935197
0.9224586408580779
0.011898303269111296


In [20]:
#Ratio final
Ratio_final_1I = f_final_1I/fprime_final_1I;
Ratio_final_2I = f_final_2I/fprime_final_2I;
Ratio_final_E = f_final_E/fprime_final_E;
print(Ratio_final_1I)
print(Ratio_final_2I)
print(Ratio_final_E)

1.1286557605307896
0.922442980850827
-0.013620277759366077


In [21]:
#1I Initial Loop
while np.abs(Ratio_initial_1I) >= Tol:
    Chi_i_initial_1I = Chi_initial_1I - Ratio_initial_1I;
    z_initial_1I = alpha_1I*Chi_i_initial_1I**2;
    C_initial_1I = (np.cosh(np.sqrt(-z_initial_1I)) - 1)/-z_initial_1I;
    S_initial_1I = (np.sinh(np.sqrt(-z_initial_1I)) - np.sqrt(-z_initial_1I))/(np.sqrt(-z_initial_1I)**3);
    f_initial_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*(Chi_i_initial_1I**2)*(C_initial_1I) + (1 - alpha_1I*r_1IM)*(Chi_i_initial_1I**3)*(S_initial_1I) + (r_1IM*Chi_i_initial_1I) - np.sqrt(mu_S)*dt_initial;
    fprime_initial_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*Chi_i_initial_1I*(1 - alpha_1I*(Chi_i_initial_1I**2)*S_initial_1I) + (1 - alpha_1I*r_1IM)*(Chi_i_initial_1I**2)*C_initial_1I + r_1IM;
    Ratio_initial_1I = f_initial_1I/fprime_initial_1I;
    Chi_initial_1I = Chi_i_initial_1I;
    Iter_initial_1I += 1;
print(Ratio_initial_1I)
print(Iter_initial_1I)
print(Chi_initial_1I)

1.6962750155884766e-12
7
5.156119158905382


In [22]:
#1I Final Loop
while np.abs(Ratio_final_1I) >= Tol:
    Chi_i_final_1I = Chi_final_1I - Ratio_final_1I;
    z_final_1I = alpha_1I*Chi_i_final_1I**2;
    C_final_1I = (np.cosh(np.sqrt(-z_final_1I)) - 1)/-z_final_1I;
    S_final_1I = (np.sinh(np.sqrt(-z_final_1I)) - np.sqrt(-z_final_1I))/(np.sqrt(-z_final_1I)**3);
    f_final_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*(Chi_i_final_1I**2)*(C_final_1I) + (1 - alpha_1I*r_1IM)*(Chi_i_final_1I**3)*(S_final_1I) + (r_1IM*Chi_i_final_1I) - np.sqrt(mu_S)*dt_final;
    fprime_final_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*Chi_i_final_1I*(1 - alpha_1I*(Chi_i_final_1I**2)*S_final_1I) + (1 - alpha_1I*r_1IM)*(Chi_i_final_1I**2)*C_final_1I + r_1IM;
    Ratio_final_1I = f_final_1I/fprime_final_1I;
    Chi_final_1I = Chi_i_final_1I;
    Iter_final_1I += 1;
print(Ratio_final_1I)
print(Iter_final_1I)
print(Chi_final_1I)

4.4093523592594005e-14
18
6.382629131986297


In [23]:
#2I Initial Loop
while np.abs(Ratio_initial_2I) >= Tol:
    Chi_i_initial_2I = Chi_initial_2I - Ratio_initial_2I;
    z_initial_2I = alpha_2I*Chi_i_initial_2I**2;
    C_initial_2I = (np.cosh(np.sqrt(-z_initial_2I)) - 1)/-z_initial_2I;
    S_initial_2I = (np.sinh(np.sqrt(-z_initial_2I)) - np.sqrt(-z_initial_2I))/(np.sqrt(-z_initial_2I)**3);
    f_initial_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*(Chi_i_initial_2I**2)*(C_initial_2I) + (1 - alpha_2I*r_2IM)*(Chi_i_initial_2I**3)*(S_initial_2I) + (r_2IM*Chi_i_initial_2I) - np.sqrt(mu_S)*dt_initial;
    fprime_initial_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*Chi_i_initial_2I*(1 - alpha_2I*(Chi_i_initial_2I**2)*S_initial_2I) + (1 - alpha_2I*r_2IM)*(Chi_i_initial_2I**2)*C_initial_2I + r_2IM;
    Ratio_initial_2I = f_initial_2I/fprime_initial_2I;
    Chi_initial_2I = Chi_i_initial_2I;
    Iter_initial_2I += 1;
print(Ratio_initial_2I)
print(Iter_initial_2I)
print(Chi_initial_2I)

-3.310283330448534e-14
16
0.6825310102435472


In [24]:
#2I Final Loop
while np.abs(Ratio_final_2I) >= Tol:
    Chi_i_final_2I = Chi_final_2I - Ratio_final_2I;
    z_final_2I = alpha_2I*Chi_i_final_2I**2;
    C_final_2I = (np.cosh(np.sqrt(-z_final_2I)) - 1)/-z_final_2I;
    S_final_2I = (np.sinh(np.sqrt(-z_final_2I)) - np.sqrt(-z_final_2I))/(np.sqrt(-z_final_2I)**3);
    f_final_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*(Chi_i_final_2I**2)*(C_final_2I) + (1 - alpha_2I*r_2IM)*(Chi_i_final_2I**3)*(S_final_2I) + (r_2IM*Chi_i_final_2I) - np.sqrt(mu_S)*dt_final;
    fprime_final_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*Chi_i_final_2I*(1 - alpha_2I*(Chi_i_final_2I**2)*S_final_2I) + (1 - alpha_2I*r_2IM)*(Chi_i_final_2I**2)*C_final_2I + r_2IM;
    Ratio_final_2I = f_final_2I/fprime_final_2I;
    Chi_final_2I = Chi_i_final_2I;
    Iter_final_2I += 1;
print(Ratio_final_2I)
print(Iter_final_2I)
print(Chi_final_2I)

6.7074295283888946e-09
34
4.48847658912458


In [25]:
#E Initial Loop
while np.abs(Ratio_initial_E) >= Tol:
    Chi_i_initial_E = Chi_initial_E - Ratio_initial_E;
    z_initial_E = alpha_E*Chi_i_initial_E**2;
    C_initial_E = (1 - np.cos(np.sqrt(z_initial_E)))/z_initial_E;
    S_initial_E = (np.sqrt(z_initial_E) - np.sin(np.sqrt(z_initial_E)))/(np.sqrt(z_initial_E)**3);
    f_initial_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*(Chi_i_initial_E**2)*(C_initial_E) + (1 - alpha_E*r_EM)*(Chi_i_initial_E**3)*(S_initial_E) + (r_EM*Chi_i_initial_E) - np.sqrt(mu_S)*dt_initial;
    fprime_initial_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*Chi_i_initial_E*(1 - alpha_E*(Chi_i_initial_E**2)*S_initial_E) + (1 - alpha_E*r_EM)*(Chi_i_initial_E**2)*C_initial_E + r_EM;
    Ratio_initial_E = f_initial_E/fprime_initial_E;
    Chi_initial_E = Chi_i_initial_E;
    Iter_initial_E += 1;
print(Ratio_initial_E)
print(Iter_initial_E)
print(Chi_initial_E)

-5.262603892710835e-15
2
10.301528166644339


In [26]:
#E Final Loop
while np.abs(Ratio_final_E) >= Tol:
    Chi_i_final_E = Chi_final_E - Ratio_final_E;
    z_final_E = alpha_E*Chi_i_final_E**2;
    C_final_E = (1 - np.cos(np.sqrt(z_final_E)))/z_final_E;
    S_final_E = (np.sqrt(z_final_E) - np.sin(np.sqrt(z_final_E)))/(np.sqrt(z_final_E)**3);
    f_final_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*(Chi_i_final_E**2)*(C_final_E) + (1 - alpha_E*r_EM)*(Chi_i_final_E**3)*(S_final_E) + (r_EM*Chi_i_final_E) - np.sqrt(mu_S)*dt_final;
    fprime_final_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*Chi_i_final_E*(1 - alpha_E*(Chi_i_final_E**2)*S_final_E) + (1 - alpha_E*r_EM)*(Chi_i_final_E**2)*C_final_E + r_EM;
    Ratio_final_E = f_final_E/fprime_final_E;
    Chi_final_E = Chi_i_final_E;
    Iter_final_E += 1;
print(Ratio_final_E)
print(Iter_final_E)
print(Chi_final_E)

1.0524784226222152e-14
2
27.51608728829896


In [27]:
#Initial f functions
f_func_initial_1I = 1 - ((Chi_initial_1I**2)/r_1IM)*C_initial_1I;
f_func_initial_2I = 1 - ((Chi_initial_2I**2)/r_2IM)*C_initial_2I;
f_func_initial_E = 1 - ((Chi_initial_E**2)/r_EM)*C_initial_E;
print(f_func_initial_1I)
print(f_func_initial_2I)
print(f_func_initial_E)

-9.941535256802489
0.9887433898238898
-0.6717558438930185


In [28]:
#Final f functions
f_func_final_1I = 1 - ((Chi_final_1I**2)/r_1IM)*C_final_1I;
f_func_final_2I = 1 - ((Chi_final_2I**2)/r_2IM)*C_final_2I;
f_func_final_E = 1 - ((Chi_final_E**2)/r_EM)*C_final_E;
print(f_func_final_1I)
print(f_func_final_2I)
print(f_func_final_E)

-31.888067816866688
-1.5108131669967277
-0.7492734656019839


In [29]:
#Initial g functions
g_func_initial_1I = dt_initial - (1/np.sqrt(mu_S))*(Chi_initial_1I**3)*S_initial_1I;
g_func_initial_2I = dt_initial - (1/np.sqrt(mu_S))*(Chi_initial_2I**3)*S_initial_2I;
g_func_initial_E = dt_initial - (1/np.sqrt(mu_S))*(Chi_initial_E**3)*S_initial_E;
print(g_func_initial_1I)
print(g_func_initial_2I)
print(g_func_initial_E)

-3045.746351144728
596.8339706383401
-43.897192381605464


In [30]:
#Final g functions
g_func_final_1I = dt_final - (1/np.sqrt(mu_S))*(Chi_final_1I**3)*S_final_1I;
g_func_final_2I = dt_final - (1/np.sqrt(mu_S))*(Chi_final_2I**3)*S_final_2I;
g_func_final_E = dt_final - (1/np.sqrt(mu_S))*(Chi_final_E**3)*S_final_E;
print(g_func_final_1I)
print(g_func_final_2I)
print(g_func_final_E)

-9868.093966419072
-1138.6931114916033
39.66711246519503


In [31]:
#Initial position vectors
r_initial_1I = f_func_initial_1I*r_1I + g_func_initial_1I*v_1I;
r_initial_2I = f_func_initial_2I*r_2I + g_func_initial_2I*v_2I;
r_initial_E = f_func_initial_E*r_E + g_func_initial_E*v_E;
print(r_initial_1I)
print(r_initial_2I)
print(r_initial_E)

[6.70922268 1.45521512 2.28395737]
[2.24893542 7.54545629 6.22130455]
[ 8.75705068e-01 -5.08488080e-01 -1.01559593e-05]


In [32]:
#Final position vectors
r_final_1I = f_func_final_1I*r_1I + g_func_final_1I*v_1I;
r_final_2I = f_func_final_2I*r_2I + g_func_final_2I*v_2I;
r_final_E = f_func_final_E*r_E + g_func_final_E*v_E;
print(r_final_1I)
print(r_final_2I)
print(r_final_E)

[21.74893252  3.69633941  8.8474451 ]
[-1.56782012 -8.90814637 -6.51998931]
[-5.47709808e-01 -8.51772265e-01  5.89354959e-05]


In [33]:
#Initial position vector magnitudes
r_initial_1IM = np.sqrt(np.dot(r_initial_1I,r_initial_1I));
r_initial_2IM = np.sqrt(np.dot(r_initial_2I,r_initial_2I));
r_initial_EM = np.sqrt(np.dot(r_initial_E,r_initial_E));
print(r_initial_1IM)
print(r_initial_2IM)
print(r_initial_EM)

7.235176660999482
10.0347521891072
1.0126299882805065


In [34]:
#Final position vector magnitudes
r_final_1IM = np.sqrt(np.dot(r_final_1I,r_final_1I));
r_final_2IM = np.sqrt(np.dot(r_final_2I,r_final_2I));
r_final_EM = np.sqrt(np.dot(r_final_E,r_final_E));
print(r_final_1IM)
print(r_final_2IM)
print(r_final_EM)

23.7688088829032
11.150040012580032
1.0126707405408886


In [35]:
#Initial fdot functions
fdot_initial_1I = (np.sqrt(mu_S)/(r_1IM*r_initial_1IM))*(alpha_1I*(Chi_initial_1I**3)*S_initial_1I - Chi_initial_1I);
fdot_initial_2I = (np.sqrt(mu_S)/(r_2IM*r_initial_2IM))*(alpha_2I*(Chi_initial_2I**3)*S_initial_2I - Chi_initial_2I);
fdot_initial_E = (np.sqrt(mu_S)/(r_EM*r_initial_EM))*(alpha_E*(Chi_initial_E**3)*S_initial_E - Chi_initial_E);
print(fdot_initial_1I)
print(fdot_initial_2I)
print(fdot_initial_E)

-0.023532060969045778
-5.91009502028427e-05
0.013240690244398532


In [36]:
#Final fdot functions
fdot_final_1I = (np.sqrt(mu_S)/(r_1IM*r_final_1IM))*(alpha_1I*(Chi_final_1I**3)*S_final_1I - Chi_final_1I);
fdot_final_2I = (np.sqrt(mu_S)/(r_2IM*r_final_2IM))*(alpha_2I*(Chi_final_2I**3)*S_final_2I - Chi_final_2I);
fdot_final_E = (np.sqrt(mu_S)/(r_EM*r_final_EM))*(alpha_E*(Chi_final_E**3)*S_final_E - Chi_final_E);
print(fdot_final_1I)
print(fdot_final_2I)
print(fdot_final_E)

-0.021236833703424135
-0.004264544777268291
-0.01201383844455548


In [37]:
#Initial gdot functions
gdot_initial_1I = 1 - ((Chi_initial_1I**2)/r_initial_1IM)*C_initial_1I;
gdot_initial_2I = 1 - ((Chi_initial_2I**2)/r_initial_2IM)*C_initial_2I;
gdot_initial_E = 1 - ((Chi_initial_E**2)/r_initial_EM)*C_initial_E;
print(gdot_initial_1I)
print(gdot_initial_2I)
print(gdot_initial_E)

-7.3100066492887255
0.9757097292895911
-0.6233974395362116


In [38]:
#Final gdot functions
gdot_final_1I = 1 - ((Chi_final_1I**2)/r_final_1IM)*C_final_1I;
gdot_final_2I = 1 - ((Chi_final_2I**2)/r_final_2IM)*C_final_2I;
gdot_final_E = 1 - ((Chi_final_E**2)/r_final_EM)*C_final_E;
print(gdot_final_1I)
print(gdot_final_2I)
print(gdot_final_E)

-6.603318574956974
-3.876063492577064
-0.6986043725178361


In [39]:
#Initial velocity vectors
v_initial_1I = fdot_initial_1I*r_1I + gdot_initial_1I*v_1I;
v_initial_2I = fdot_initial_2I*r_2I + gdot_initial_2I*v_2I;
v_initial_E = fdot_initial_E*r_E + gdot_initial_E*v_E;
print(v_initial_1I)
print(v_initial_2I)
print(v_initial_E)

[0.01611415 0.00245443 0.00695715]
[-0.00846997 -0.01214484 -0.01369318]
[ 8.34446639e-03  1.48028773e-02 -9.79971768e-07]


In [40]:
#Final velocity vectors
v_final_1I = fdot_final_1I*r_1I + gdot_final_1I*v_1I;
v_final_2I = fdot_final_2I*r_2I + gdot_final_2I*v_2I;
v_final_E = fdot_final_E*r_E + gdot_final_E*v_E;
print(v_final_1I)
print(v_final_2I)
print(v_final_E)

[0.01455705 0.00215301 0.00637575]
[ 0.00102969 -0.0174919  -0.00968579]
[ 1.41741126e-02 -9.37156927e-03 -1.13085744e-07]


In [41]:
#Initial velocity vector magnitudes
v_initial_1IM = np.sqrt(np.dot(v_initial_1I,v_initial_1I));
v_initial_2IM = np.sqrt(np.dot(v_initial_2I,v_initial_2I));
v_initial_EM = np.sqrt(np.dot(v_initial_E,v_initial_E));
print(v_initial_1IM)
print(v_initial_2IM)
print(v_initial_EM)

0.017722645208019597
0.020167816957524155
0.016992801340955817


In [42]:
#Final velocity vector magnitudes
v_final_1IM = np.sqrt(np.dot(v_final_1I,v_final_1I));
v_final_2IM = np.sqrt(np.dot(v_final_2I,v_final_2I));
v_final_EM = np.sqrt(np.dot(v_final_E,v_final_E));
print(v_final_1IM)
print(v_final_2IM)
print(v_final_EM)

0.01603724285861022
0.020021028747810588
0.016992109287881328


In [43]:
#Problem 2
#Position cross products (AU^2)
r1r2_cross_1I = np.cross(r_initial_1I,r_final_1I);
r1r2_cross_2I = np.cross(r_initial_2I,r_final_2I);
r1r2_cross_E = np.cross(r_initial_E,r_final_E);
print(r1r2_cross_1I)
print(r1r2_cross_2I)
print(r1r2_cross_E)

[ 4.43265427 -9.68584463 -6.84981131]
[ 6.22399709  4.90914852 -8.20392778]
[-3.86185616e-05 -4.60475939e-05 -1.02440520e+00]


In [44]:
#Position dot products (AU^2)
r1r2_dot_1I = np.dot(r_initial_1I,r_final_1I);
r1r2_dot_2I = np.dot(r_initial_2I,r_final_2I);
r1r2_dot_E = np.dot(r_initial_E,r_final_E);
print(r1r2_dot_1I)
print(r1r2_dot_2I)
print(r1r2_dot_E)

171.50458783621474
-111.3047944441092
-0.0465162124420952


In [45]:
#Position multiplications (AU^2)
r1r2_1IM = r_initial_1IM*r_final_1IM;
r1r2_2IM = r_initial_2IM*r_final_2IM;
r1r2_EM = r_initial_EM*r_final_EM;
print(r1r2_1IM)
print(r1r2_2IM)
print(r1r2_EM)

171.9715312893384
111.88788842487035
1.0254607601259318


In [46]:
#Validity checks
dtheta_1I_in = r1r2_dot_1I/r1r2_1IM;
dtheta_2I_in = r1r2_dot_2I/r1r2_2IM;
dtheta_E_in = r1r2_dot_E/r1r2_EM;
if dtheta_1I_in >= 1:
    dtheta_1I_in = 0.99;
if dtheta_1I_in <= -1:
    dtheta_1I_in = -0.99;
if dtheta_2I_in >= 1:
    dtheta_2I_in = 0.99;
if dtheta_2I_in <= -1:
    dtheta_2I_in = -0.99;
if dtheta_E_in >= 1:
    dtheta_E_in = 0.99;
if dtheta_E_in <= -1:
    dtheta_E_in = -0.99;

In [47]:
#Prograde change in true anomaly, 1I (Rad)
if r1r2_cross_1I[2] >= 0:
    dtheta_1I_pg = np.arccos(dtheta_1I_in);
else:
    dtheta_1I_pg = 2*np.pi - np.arccos(dtheta_1I_in);
print(dtheta_1I_pg)

6.209476873807698


In [48]:
#Retrograde change in true anomaly, 1I (Rad)
if r1r2_cross_1I[2] < 0:
    dtheta_1I_rg = np.arccos(dtheta_2I_in);
else:
    dtheta_1I_rg = 2*np.pi - np.arccos(dtheta_2I_in);
print(dtheta_1I_rg)

3.0394560232066845


In [49]:
#Prograde change in true anomaly, 2I (Rad)
if r1r2_cross_2I[2] >= 0:
    dtheta_2I_pg = np.arccos(dtheta_E_in);
else:
    dtheta_2I_pg = 2*np.pi - np.arccos(dtheta_E_in);
print(dtheta_2I_pg)

4.667012129943819


In [50]:
#Retrograde change in true anomaly, 2I (Rad)
if r1r2_cross_2I[2] < 0:
    dtheta_2I_rg = np.arccos(r1r2_dot_2I/r1r2_2IM);
else:
    dtheta_2I_rg = 2*np.pi - np.arccos(r1r2_dot_2I/r1r2_2IM);
print(dtheta_2I_rg)

3.0394560232066845


In [51]:
#Prograde change in true anomaly, E (Rad)
if r1r2_cross_E[2] >= 0:
    dtheta_E_pg = np.arccos(r1r2_dot_E/r1r2_EM);
else:
    dtheta_E_pg = 2*np.pi - np.arccos(r1r2_dot_E/r1r2_EM);
print(dtheta_E_pg)

4.667012129943819


In [52]:
#Retrograde change in true anomaly, E (Rad)
if r1r2_cross_E[2] < 0:
    dtheta_E_rg = np.arccos(r1r2_dot_E/r1r2_EM);
else:
    dtheta_E_rg = 2*np.pi - np.arccos(r1r2_dot_E/r1r2_EM);
print(dtheta_E_rg)

1.6161731772357677


In [53]:
#Prograde A, constant
A_1I_pg = np.sin(dtheta_1I_pg)*np.sqrt((r1r2_1IM)/(1 - np.cos(dtheta_1I_pg)));
A_2I_pg = np.sin(dtheta_2I_pg)*np.sqrt((r1r2_2IM)/(1 - np.cos(dtheta_2I_pg)));
A_E_pg = np.sin(dtheta_E_pg)*np.sqrt((r1r2_EM)/(1 - np.cos(dtheta_E_pg)));
print(A_1I_pg)
print(A_2I_pg)
print(A_E_pg)

-18.533108728045388
-10.335013817803434
-0.9894162661306093


In [54]:
#Retrograde A, constant
A_1I_rg = np.sin(dtheta_1I_rg)*np.sqrt((r1r2_1IM)/(1 - np.cos(dtheta_1I_rg)));
A_2I_rg = np.sin(dtheta_2I_rg)*np.sqrt((r1r2_2IM)/(1 - np.cos(dtheta_2I_rg)));
A_E_rg = np.sin(dtheta_E_rg)*np.sqrt((r1r2_EM)/(1 - np.cos(dtheta_E_rg)));
print(A_1I_rg)
print(A_2I_rg)
print(A_E_rg)

0.9466861411993047
0.763605906709177
0.9894162661306092


In [55]:
#Prograde C Constants
if Z_1I_pg > 0:
    C_1I_pg = (1 - np.cos(np.sqrt(Z_1I_pg)))/Z_1I_pg;
if Z_1I_pg < 0:
    C_1I_pg = (np.cosh(np.sqrt(-Z_1I_pg)) - 1)/-Z_1I_pg;
if Z_1I_pg == 0:
    C_1I_pg = 0.5;
if Z_2I_pg > 0:
    C_2I_pg = (1 - np.cos(np.sqrt(Z_2I_pg)))/Z_2I_pg;
if Z_2I_pg < 0:
    C_2I_pg = (np.cosh(np.sqrt(-Z_2I_pg)) - 1)/-Z_2I_pg;
if Z_2I_pg == 0:
    C_2I_pg = 0.5;
if Z_E_pg > 0:
    C_E_pg = (1 - np.cos(np.sqrt(Z_E_pg)))/Z_E_pg;
if Z_E_pg < 0:
    C_E_pg = (np.cosh(np.sqrt(-Z_E_pg)) - 1)/-Z_E_pg;
if Z_E_pg == 0:
    C_E_pg = 0.5;
print(C_1I_pg)
print(C_2I_pg)
print(C_E_pg)

0.4405426740087018
0.4405426740087018
0.4405426740087018


In [56]:
#Retrograde C Constants
if Z_1I_rg > 0:
    C_1I_rg = (1 - np.cos(np.sqrt(Z_1I_rg)))/Z_1I_rg;
if Z_1I_rg < 0:
    C_1I_rg = (np.cosh(np.sqrt(-Z_1I_rg)) - 1)/-Z_1I_rg;
if Z_1I_rg == 0:
    C_1I_rg = 0.5;
if Z_2I_rg > 0:
    C_2I_rg = (1 - np.cos(np.sqrt(Z_2I_rg)))/Z_2I_rg;
if Z_2I_rg < 0:
    C_2I_rg = (np.cosh(np.sqrt(-Z_2I_rg)) - 1)/-Z_2I_rg;
if Z_2I_rg == 0:
    C_2I_rg = 0.5;
if Z_E_rg > 0:
    C_E_rg = (1 - np.cos(np.sqrt(Z_E_rg)))/Z_E_rg;
if Z_E_rg < 0:
    C_E_rg = (np.cosh(np.sqrt(-Z_E_rg)) - 1)/-Z_E_rg;
if Z_E_rg == 0:
    C_E_rg = 0.5;
print(C_1I_rg)
print(C_2I_rg)
print(C_E_rg)

0.4405426740087018
0.4405426740087018
0.4405426740087018


In [57]:
#Prograde S Constants
if Z_1I_pg > 0:
    S_1I_pg = (np.sqrt(Z_1I_pg) - np.sin(np.sqrt(Z_1I_pg)))/(np.sqrt(Z_1I_pg)**3);
if Z_1I_pg < 0:
    S_1I_pg = (np.sinh(np.sqrt(-Z_1I_pg)) - np.sqrt(-Z_1I_pg))/(np.sqrt(-Z_1I_pg)**3);
if Z_1I_pg == 0:
    S_1I_pg = 1/6;
if Z_2I_pg > 0:
    S_2I_pg = (np.sqrt(Z_2I_pg) - np.sin(np.sqrt(Z_2I_pg)))/(np.sqrt(Z_2I_pg)**3);
if Z_2I_pg < 0:
    S_2I_pg = (np.sinh(np.sqrt(-Z_2I_pg)) - np.sqrt(-Z_2I_pg))/(np.sqrt(-Z_2I_pg)**3);
if Z_2I_pg == 0:
    S_2I_pg = 1/6;
if Z_E_pg > 0:
    S_E_pg = (np.sqrt(Z_E_pg) - np.sin(np.sqrt(Z_E_pg)))/(np.sqrt(Z_E_pg)**3);
if Z_E_pg < 0:
    S_E_pg = (np.sinh(np.sqrt(-Z_E_pg)) - np.sqrt(-Z_E_pg))/(np.sqrt(-Z_E_pg)**3);
if Z_E_pg == 0:
    S_E_pg = 1/6;
print(S_1I_pg)
print(S_2I_pg)
print(S_E_pg)

0.15460392025833494
0.15460392025833494
0.15460392025833494


In [58]:
#Retrograde S Constants
if Z_1I_rg > 0:
    S_1I_rg = (np.sqrt(Z_1I_rg) - np.sin(np.sqrt(Z_1I_rg)))/(np.sqrt(Z_1I_rg)**3);
if Z_1I_rg < 0:
    S_1I_rg = (np.sinh(np.sqrt(-Z_1I_rg)) - np.sqrt(-Z_1I_rg))/(np.sqrt(-Z_1I_rg)**3);
if Z_1I_rg == 0:
    S_1I_rg = 1/6;
if Z_2I_rg > 0:
    S_2I_rg = (np.sqrt(Z_2I_rg) - np.sin(np.sqrt(Z_2I_rg)))/(np.sqrt(Z_2I_rg)**3);
if Z_2I_rg < 0:
    S_2I_rg = (np.sinh(np.sqrt(-Z_2I_rg)) - np.sqrt(-Z_2I_rg))/(np.sqrt(-Z_2I_rg)**3);
if Z_2I_rg == 0:
    S_2I_rg = 1/6;
if Z_E_rg > 0:
    S_E_rg = (np.sqrt(Z_E_rg) - np.sin(np.sqrt(Z_E_rg)))/(np.sqrt(Z_E_rg)**3);
if Z_E_rg < 0:
    S_E_rg = (np.sinh(np.sqrt(-Z_E_rg)) - np.sqrt(-Z_E_rg))/(np.sqrt(-Z_E_rg)**3);
if Z_E_rg == 0:
    S_E_rg = 1/6;
print(S_1I_rg)
print(S_2I_rg)
print(S_E_rg)

0.15460392025833494
0.15460392025833494
0.15460392025833494


In [59]:
#Prograde y functions
y_1I_pg = r_1IM + r_final_1IM + A_1I_pg*((Z_1I_pg*S_1I_pg - 1)/np.sqrt(C_1I_pg));
y_2I_pg = r_2IM + r_final_2IM + A_2I_pg*((Z_2I_pg*S_2I_pg - 1)/np.sqrt(C_2I_pg));
y_E_pg = r_EM + r_final_EM + A_E_pg*((Z_E_pg*S_E_pg - 1)/np.sqrt(C_E_pg));
print(y_1I_pg)
print(y_2I_pg)
print(y_E_pg)

50.71097363238845
44.763712459501875
3.1409928717945688


In [60]:
#Retrograde y functions
y_1I_rg = r_initial_1IM + r_final_1IM + A_1I_rg*((Z_1I_rg*S_1I_rg - 1)/np.sqrt(C_1I_rg));
y_2I_rg = r_initial_2IM + r_final_2IM + A_2I_rg*((Z_2I_rg*S_2I_rg - 1)/np.sqrt(C_2I_rg));
y_E_rg = r_initial_EM + r_final_EM + A_E_rg*((Z_E_rg*S_E_rg - 1)/np.sqrt(C_E_rg));
print(y_1I_rg)
print(y_2I_rg)
print(y_E_rg)

29.908450011698033
20.30112298229688
0.880316527073022


In [61]:
#Prograde Fs
F_1I_pg = ((y_1I_pg/C_1I_pg)**1.5)*S_1I_pg + A_1I_pg*np.sqrt(y_1I_pg) - np.sqrt(mu_S)*dt;
F_2I_pg = ((y_2I_pg/C_2I_pg)**1.5)*S_2I_pg + A_2I_pg*np.sqrt(y_2I_pg) - np.sqrt(mu_S)*dt;
F_E_pg = ((y_E_pg/C_E_pg)**1.5)*S_E_pg + A_E_pg*np.sqrt(y_E_pg) - np.sqrt(mu_S)*dt;
print(F_1I_pg)
print(F_2I_pg)
print(F_E_pg)

41.758194300242366
72.00428100938738
-16.012296234148383


In [62]:
#Retrograde Fs
F_1I_rg = ((y_1I_rg/C_1I_rg)**1.5)*S_1I_rg + A_1I_rg*np.sqrt(y_1I_rg) - np.sqrt(mu_S)*dt;
F_2I_rg = ((y_2I_rg/C_2I_rg)**1.5)*S_2I_rg + A_2I_rg*np.sqrt(y_2I_rg) - np.sqrt(mu_S)*dt;
F_E_rg = ((y_E_rg/C_E_rg)**1.5)*S_E_rg + A_E_rg*np.sqrt(y_E_rg) - np.sqrt(mu_S)*dt;
print(F_1I_rg)
print(F_2I_rg)
print(F_E_rg)

74.45792598381334
34.60206235436736
-15.837063615943078


In [63]:
#Prograde Fprimes
if Z_1I_pg != 0:
    Fprime_1I_pg = ((y_1I_pg/C_1I_pg)**1.5)*((1/(2*Z_1I_pg))*(C_1I_pg - 1.5*(S_1I_pg/C_1I_pg)) + 0.75*((S_1I_pg**2)/C_1I_pg)) + (A_1I_pg/8)*(3*(S_1I_pg/C_1I_pg)*np.sqrt(y_1I_pg) + A_1I_pg*np.sqrt(C_1I_pg/y_1I_pg));
else:
    Fprime_1I_pg = (np.sqrt(2)/40)*y_1I_pg + (A_1I_pg/8)*(np.sqrt(y_1I_pg) + A_1I_pg*np.sqrt(1/(2*y_1I_pg)));
if Z_2I_pg != 0:
    Fprime_2I_pg = ((y_2I_pg/C_2I_pg)**1.5)*((1/(2*Z_2I_pg))*(C_2I_pg - 1.5*(S_2I_pg/C_2I_pg)) + 0.75*((S_2I_pg**2)/C_2I_pg)) + (A_2I_pg/8)*(3*(S_2I_pg/C_2I_pg)*np.sqrt(y_2I_pg) + A_2I_pg*np.sqrt(C_2I_pg/y_2I_pg));
else:
    Fprime_2I_pg = (np.sqrt(2)/40)*y_2I_pg + (A_2I_pg/8)*(np.sqrt(y_2I_pg) + A_2I_pg*np.sqrt(1/(2*y_2I_pg)));
if Z_E_pg != 0:
    Fprime_E_pg = ((y_E_pg/C_E_pg)**1.5)*((1/(2*Z_E_pg))*(C_E_pg - 1.5*(S_E_pg/C_E_pg)) + 0.75*((S_E_pg**2)/C_E_pg)) + (A_E_pg/8)*(3*(S_E_pg/C_E_pg)*np.sqrt(y_E_pg) + A_E_pg*np.sqrt(C_E_pg/y_E_pg));
else:
    Fprime_E_pg = (np.sqrt(2)/40)*y_E_pg + (A_E_pg/8)*(np.sqrt(y_E_pg) + A_E_pg*np.sqrt(1/(2*y_E_pg)));
print(Fprime_1I_pg)
print(Fprime_2I_pg)
print(Fprime_E_pg)

1.5400423519070223
4.5875358921145715
0.04485018050709211


In [64]:
#Retrograde Fprimes
if Z_1I_rg != 0:
    Fprime_1I_rg = ((y_1I_rg/C_1I_rg)**1.5)*((1/(2*Z_1I_rg))*(C_1I_rg - 1.5*(S_1I_rg/C_1I_rg)) + 0.75*((S_1I_rg**2)/C_1I_rg)) + (A_1I_rg/8)*(3*(S_1I_rg/C_1I_rg)*np.sqrt(y_1I_rg) + A_1I_rg*np.sqrt(C_1I_rg/y_1I_rg));
else:
    Fprime_1I_rg = (np.sqrt(2)/40)*y_1I_rg + (A_1I_rg/8)*(np.sqrt(y_1I_rg) + A_1I_rg*np.sqrt(1/(2*y_1I_rg)));
if Z_2I_rg != 0:
    Fprime_2I_rg = ((y_2I_rg/C_2I_rg)**1.5)*((1/(2*Z_2I_rg))*(C_2I_rg - 1.5*(S_2I_rg/C_2I_rg)) + 0.75*((S_2I_rg**2)/C_2I_rg)) + (A_2I_rg/8)*(3*(S_2I_rg/C_2I_rg)*np.sqrt(y_2I_rg) + A_2I_rg*np.sqrt(C_2I_rg/y_2I_rg));
else:
    Fprime_2I_rg = (np.sqrt(2)/40)*y_2I_rg + (A_2I_rg/8)*(np.sqrt(y_2I_rg) + A_2I_rg*np.sqrt(1/(2*y_2I_rg)));
if Z_E_rg != 0:
    Fprime_E_rg = ((y_E_rg/C_E_rg)**1.5)*((1/(2*Z_E_rg))*(C_E_rg - 1.5*(S_E_rg/C_E_rg)) + 0.75*((S_E_rg**2)/C_E_rg)) + (A_E_rg/8)*(3*(S_E_rg/C_E_rg)*np.sqrt(y_E_rg) + A_E_rg*np.sqrt(C_E_rg/y_E_rg));
else:
    Fprime_E_rg = (np.sqrt(2)/40)*y_E_rg + (A_E_rg/8)*(np.sqrt(y_E_rg) + A_E_rg*np.sqrt(1/(2*y_E_rg)));
print(Fprime_1I_rg)
print(Fprime_2I_rg)
print(Fprime_E_rg)

7.446795330967194
4.239352059943604
0.24282940088477625


In [65]:
#Prograde Ratios
Ratio_1I_pg = F_1I_pg/Fprime_1I_pg;
Ratio_2I_pg = F_2I_pg/Fprime_2I_pg;
Ratio_E_pg = F_E_pg/Fprime_E_pg;
print(Ratio_1I_pg)
print(Ratio_2I_pg)
print(Ratio_E_pg)

27.114964889461334
15.695633277366653
-357.01743121449374


In [66]:
#Retrograde Ratios
Ratio_1I_rg = F_1I_rg/Fprime_1I_rg;
Ratio_2I_rg = F_2I_rg/Fprime_2I_rg;
Ratio_E_rg = F_E_rg/Fprime_E_rg;
print(Ratio_1I_rg)
print(Ratio_2I_rg)
print(Ratio_E_rg)

9.998653471001559
8.162111064403478
-65.21888847989146


In [67]:
#Prograde 1I Loop
while np.abs(Ratio_1I_pg) >= Tol:
    Z_i_1I_pg = Z_1I_pg - Ratio_1I_pg;
    if Z_i_1I_pg > 0:
        C_i_1I_pg = (1 - np.cos(np.sqrt(Z_i_1I_pg)))/Z_i_1I_pg;
    if Z_i_1I_pg < 0:
        C_i_1I_pg = (np.cosh(np.sqrt(-Z_i_1I_pg)) - 1)/-Z_i_1I_pg;
    if Z_i_1I_pg == 0:
        C_i_1I_pg = 0.5;
    if Z_i_1I_pg > 0:
        S_i_1I_pg = (np.sqrt(Z_i_1I_pg) - np.sin(np.sqrt(Z_i_1I_pg)))/(np.sqrt(Z_i_1I_pg)**3);
    if Z_i_1I_pg < 0:
        S_i_1I_pg = (np.sinh(np.sqrt(-Z_i_1I_pg)) - np.sqrt(-Z_i_1I_pg))/(np.sqrt(-Z_i_1I_pg)**3);
    if Z_i_1I_pg == 0:
        S_i_1I_pg = 1/6;
    y_i_1I_pg = r_initial_1IM + r_final_1IM + A_1I_pg*((Z_i_1I_pg*S_i_1I_pg - 1)/np.sqrt(C_i_1I_pg));
    if y_i_1I_pg <= 0:
        Z_1I_pg = Z_1I_pg;
        C_1I_pg = C_1I_pg;
        S_1I_pg = S_1I_pg;
        y_1I_pg = y_1I_pg;
        F_1I_pg = F_1I_pg;
        Fprime_1I_pg = Fprime_1I_pg;
        Ratio_1I_pg = Ratio_1I_pg;
        break
    if y_i_1I_pg >= 1.0E16:
        Z_1I_pg = Z_1I_pg;
        C_1I_pg = C_1I_pg;
        S_1I_pg = S_1I_pg;
        y_1I_pg = y_1I_pg;
        F_1I_pg = F_1I_pg;
        Fprime_1I_pg = Fprime_1I_pg;
        Ratio_1I_pg = Ratio_1I_pg;
        break
    F_i_1I_pg = ((y_i_1I_pg/C_i_1I_pg)**1.5)*S_i_1I_pg + A_1I_pg*np.sqrt(y_i_1I_pg) - np.sqrt(mu_S)*dt;
    if Z_i_1I_pg != 0:
        Fprime_i_1I_pg = ((y_i_1I_pg/C_i_1I_pg)**1.5)*((1/(2*Z_i_1I_pg))*(C_i_1I_pg - 1.5*(S_i_1I_pg/C_i_1I_pg)) + 0.75*((S_i_1I_pg**2)/C_i_1I_pg)) + (A_1I_pg/8)*(3*(S_i_1I_pg/C_i_1I_pg)*np.sqrt(y_i_1I_pg) + A_1I_pg*np.sqrt(C_i_1I_pg/y_i_1I_pg));
    else:
        Fprime_i_1I_pg = (np.sqrt(2)/40)*y_i_1I_pg + (A_1I_pg/8)*(np.sqrt(y_i_1I_pg) + A_1I_pg*np.sqrt(1/(2*y_i_1I_pg)));
    Ratio_1I_pg = F_i_1I_pg/Fprime_i_1I_pg;
    Z_1I_pg = Z_i_1I_pg;
    C_1I_pg = C_i_1I_pg;
    S_1I_pg = S_i_1I_pg;
    y_1I_pg = y_i_1I_pg;
    F_1I_pg = F_i_1I_pg;
    Fprime_1I_pg = Fprime_i_1I_pg;
    Ratio_1I_pg = Ratio_1I_pg;
    Iter_1I_pg += 1;
    if Iter_1I_pg >= 100:
        Z_1I_pg = Z_1I_pg;
        C_1I_pg = C_1I_pg;
        S_1I_pg = S_1I_pg;
        y_1I_pg = y_1I_pg;
        F_1I_pg = F_1I_pg;
        Fprime_1I_pg = Fprime_1I_pg;
        Ratio_1I_pg = Ratio_1I_pg;
        break
print(Ratio_1I_pg)
print(Iter_1I_pg)
print(Z_1I_pg)

1.093171414272865e-10
6
-74.44693333426181


In [68]:
#Prograde 2I Loop
while np.abs(Ratio_2I_pg) >= Tol:
    Z_i_2I_pg = Z_2I_pg - Ratio_2I_pg;
    if Z_i_2I_pg > 0:
        C_i_2I_pg = (1 - np.cos(np.sqrt(Z_i_2I_pg)))/Z_i_2I_pg;
    if Z_i_2I_pg < 0:
        C_i_2I_pg = (np.cosh(np.sqrt(-Z_i_2I_pg)) - 1)/-Z_i_2I_pg;
    if Z_i_2I_pg == 0:
        C_i_2I_pg = 0.5;
    if Z_i_2I_pg > 0:
        S_i_2I_pg = (np.sqrt(Z_i_2I_pg) - np.sin(np.sqrt(Z_i_2I_pg)))/(np.sqrt(Z_i_2I_pg)**3);
    if Z_i_2I_pg < 0:
        S_i_2I_pg = (np.sinh(np.sqrt(-Z_i_2I_pg)) - np.sqrt(-Z_i_2I_pg))/(np.sqrt(-Z_i_2I_pg)**3);
    if Z_i_2I_pg == 0:
        S_i_2I_pg = 1/6;
    y_i_2I_pg = r_initial_2IM + r_final_2IM + A_2I_pg*((Z_i_2I_pg*S_i_2I_pg - 1)/np.sqrt(C_i_2I_pg));
    if y_i_2I_pg <= 0:
        Z_2I_pg = Z_2I_pg;
        C_2I_pg = C_2I_pg;
        S_2I_pg = S_2I_pg;
        y_2I_pg = y_2I_pg;
        F_2I_pg = F_2I_pg;
        Fprime_2I_pg = Fprime_2I_pg;
        Ratio_2I_pg = Ratio_2I_pg;
        break
    if y_i_2I_pg >= 1.0E16:
        Z_2I_pg = Z_2I_pg;
        C_2I_pg = C_2I_pg;
        S_2I_pg = S_2I_pg;
        y_2I_pg = y_2I_pg;
        F_2I_pg = F_2I_pg;
        Fprime_2I_pg = Fprime_2I_pg;
        Ratio_2I_pg = Ratio_2I_pg;
        break
    F_i_2I_pg = ((y_i_2I_pg/C_i_2I_pg)**1.5)*S_i_2I_pg + A_2I_pg*np.sqrt(y_i_2I_pg) - np.sqrt(mu_S)*dt;
    if Z_i_2I_pg != 0:
        Fprime_i_2I_pg = ((y_i_2I_pg/C_i_2I_pg)**1.5)*((1/(2*Z_i_2I_pg))*(C_i_2I_pg - 1.5*(S_i_2I_pg/C_i_2I_pg)) + 0.75*((S_i_2I_pg**2)/C_i_2I_pg)) + (A_2I_pg/8)*(3*(S_i_2I_pg/C_i_2I_pg)*np.sqrt(y_i_2I_pg) + A_2I_pg*np.sqrt(C_i_2I_pg/y_i_2I_pg));
    else:
        Fprime_i_2I_pg = (np.sqrt(2)/40)*y_i_2I_pg + (A_2I_pg/8)*(np.sqrt(y_i_2I_pg) + A_2I_pg*np.sqrt(1/(2*y_i_2I_pg)));
    Ratio_2I_pg = F_i_2I_pg/Fprime_i_2I_pg;
    Z_2I_pg = Z_i_2I_pg;
    C_2I_pg = C_i_2I_pg;
    S_2I_pg = S_i_2I_pg;
    y_2I_pg = y_i_2I_pg;
    F_2I_pg = F_i_2I_pg;
    Fprime_2I_pg = Fprime_i_2I_pg;
    Ratio_2I_pg = Ratio_2I_pg;
    Iter_2I_pg += 1;
    if Iter_2I_pg >= 100:
        Z_2I_pg = Z_2I_pg;
        C_2I_pg = C_2I_pg;
        S_2I_pg = S_2I_pg;
        y_2I_pg = y_2I_pg;
        F_2I_pg = F_2I_pg;
        Fprime_2I_pg = Fprime_2I_pg;
        Ratio_2I_pg = Ratio_2I_pg;
        break
print(Ratio_2I_pg)
print(Iter_2I_pg)
print(Z_2I_pg)

-8.789654559019744e-14
6
-32.83360382492818


In [69]:
#Prograde E Loop
while np.abs(Ratio_E_pg) >= Tol:
    Z_i_E_pg = Z_E_pg - Ratio_E_pg;
    if Z_i_E_pg > 0:
        C_i_E_pg = (1 - np.cos(np.sqrt(Z_i_E_pg)))/Z_i_E_pg;
    if Z_i_E_pg < 0:
        C_i_E_pg = (np.cosh(np.sqrt(-Z_i_E_pg)) - 1)/-Z_i_E_pg;
    if Z_i_E_pg == 0:
        C_i_E_pg = 0.5;
    if Z_i_E_pg > 0:
        S_i_E_pg = (np.sqrt(Z_i_E_pg) - np.sin(np.sqrt(Z_i_E_pg)))/(np.sqrt(Z_i_E_pg)**3);
    if Z_i_E_pg < 0:
        S_i_E_pg = (np.sinh(np.sqrt(-Z_i_E_pg)) - np.sqrt(-Z_i_E_pg))/(np.sqrt(-Z_i_E_pg)**3);
    if Z_i_E_pg == 0:
        S_i_E_pg = 1/6;
    y_i_E_pg = r_initial_EM + r_final_EM + A_E_pg*((Z_i_E_pg*S_i_E_pg - 1)/np.sqrt(C_i_E_pg));
    if y_i_E_pg <= 0:
        Z_E_pg = Z_E_pg;
        C_E_pg = C_E_pg;
        S_E_pg = S_E_pg;
        y_E_pg = y_E_pg;
        F_E_pg = F_E_pg;
        Fprime_E_pg = Fprime_E_pg;
        Ratio_E_pg = Ratio_E_pg;
        break
    if y_i_E_pg >= 1.0E16:
        Z_E_pg = Z_E_pg;
        C_E_pg = C_E_pg;
        S_E_pg = S_E_pg;
        y_E_pg = y_E_pg;
        F_E_pg = F_E_pg;
        Fprime_E_pg = Fprime_E_pg;
        Ratio_E_pg = Ratio_E_pg;
        break
    F_i_E_pg = ((y_i_E_pg/C_i_E_pg)**1.5)*S_i_E_pg + A_E_pg*np.sqrt(y_i_E_pg) - np.sqrt(mu_S)*dt;
    if Z_i_E_pg != 0:
        Fprime_i_E_pg = ((y_i_E_pg/C_i_E_pg)**1.5)*((1/(2*Z_i_E_pg))*(C_i_E_pg - 1.5*(S_i_E_pg/C_i_E_pg)) + 0.75*((S_i_E_pg**2)/C_i_E_pg)) + (A_E_pg/8)*(3*(S_i_E_pg/C_i_E_pg)*np.sqrt(y_i_E_pg) + A_E_pg*np.sqrt(C_i_E_pg/y_i_E_pg));
    else:
        Fprime_i_E_pg = (np.sqrt(2)/40)*y_i_E_pg + (A_E_pg/8)*(np.sqrt(y_i_E_pg) + A_E_pg*np.sqrt(1/(2*y_i_E_pg)));
    Ratio_E_pg = F_i_E_pg/Fprime_i_E_pg;
    Z_E_pg = Z_i_E_pg;
    C_E_pg = C_i_E_pg;
    S_E_pg = S_i_E_pg;
    y_E_pg = y_i_E_pg;
    F_E_pg = F_i_E_pg;
    Fprime_E_pg = Fprime_i_E_pg;
    Ratio_E_pg = Ratio_E_pg;
    Iter_E_pg += 1;
    if Iter_E_pg >= 100:
        Z_E_pg = Z_E_pg;
        C_E_pg = C_E_pg;
        S_E_pg = S_E_pg;
        y_E_pg = y_E_pg;
        F_E_pg = F_E_pg;
        Fprime_E_pg = Fprime_E_pg;
        Ratio_E_pg = Ratio_E_pg;
        break
print(Ratio_1I_pg)
print(Iter_1I_pg)
print(Z_1I_pg)

1.093171414272865e-10
6
-74.44693333426181


In [70]:
#Retrograde 1I Loop
while np.abs(Ratio_1I_rg) >= Tol:
    Z_i_1I_rg = Z_1I_rg - Ratio_1I_rg;
    if Z_i_1I_rg > 0:
        C_i_1I_rg = (1 - np.cos(np.sqrt(Z_i_1I_rg)))/Z_i_1I_rg;
    if Z_i_1I_rg < 0:
        C_i_1I_rg = (np.cosh(np.sqrt(-Z_i_1I_rg)) - 1)/-Z_i_1I_rg;
    if Z_i_1I_rg == 0:
        C_i_1I_rg = 0.5;
    if Z_i_1I_rg > 0:
        S_i_1I_rg = (np.sqrt(Z_i_1I_rg) - np.sin(np.sqrt(Z_i_1I_rg)))/(np.sqrt(Z_i_1I_rg)**3);
    if Z_i_1I_rg < 0:
        S_i_1I_rg = (np.sinh(np.sqrt(-Z_i_1I_rg)) - np.sqrt(-Z_i_1I_rg))/(np.sqrt(-Z_i_1I_rg)**3);
    if Z_i_1I_rg == 0:
        S_i_1I_rg = 1/6;
    y_i_1I_rg = r_initial_1IM + r_final_1IM + A_1I_rg*((Z_i_1I_rg*S_i_1I_rg - 1)/np.sqrt(C_i_1I_rg));
    if y_i_1I_rg >= 1.0E16:
        Z_1I_rg = Z_1I_rg;
        C_1I_rg = C_1I_rg;
        S_1I_rg = S_1I_rg;
        y_1I_rg = y_1I_rg;
        F_1I_rg = F_1I_rg;
        Fprime_1I_rg = Fprime_1I_rg;
        Ratio_1I_rg = Ratio_1I_rg;
        break
    F_i_1I_rg = ((y_i_1I_rg/C_i_1I_rg)**1.5)*S_i_1I_rg + A_1I_rg*np.sqrt(y_i_1I_rg) - np.sqrt(mu_S)*dt;
    if Z_i_1I_rg != 0:
        Fprime_i_1I_rg = ((y_i_1I_rg/C_i_1I_rg)**1.5)*((1/(2*Z_i_1I_rg))*(C_i_1I_rg - 1.5*(S_i_1I_rg/C_i_1I_rg)) + 0.75*((S_i_1I_rg**2)/C_i_1I_rg)) + (A_1I_rg/8)*(3*(S_i_1I_rg/C_i_1I_rg)*np.sqrt(y_i_1I_rg) + A_1I_rg*np.sqrt(C_i_1I_rg/y_i_1I_rg));
    else:
        Fprime_i_1I_rg = (np.sqrt(2)/40)*y_i_1I_rg + (A_1I_rg/8)*(np.sqrt(y_i_1I_rg) + A_1I_rg*np.sqrt(1/(2*y_i_1I_rg)));
    Ratio_1I_rg = F_i_1I_rg/Fprime_i_1I_rg;
    Z_1I_rg = Z_i_1I_rg;
    C_1I_rg = C_i_1I_rg;
    S_1I_rg = S_i_1I_rg;
    y_1I_rg = y_i_1I_rg;
    F_1I_rg = F_i_1I_rg;
    Fprime_1I_rg = Fprime_i_1I_rg;
    Ratio_1I_rg = Ratio_1I_rg;
    Iter_1I_rg += 1;
    if Iter_1I_rg >= 100:
        Z_1I_rg = Z_1I_rg;
        C_1I_rg = C_1I_rg;
        S_1I_rg = S_1I_rg;
        y_1I_rg = y_1I_rg;
        F_1I_rg = F_1I_rg;
        Fprime_1I_rg = Fprime_1I_rg;
        Ratio_1I_rg = Ratio_1I_rg;
        break
print(Ratio_1I_rg)
print(Iter_1I_rg)
print(Z_1I_rg)

1.1587878355673313e-10
6
-24.295403517512252


In [71]:
#Retrograde 2I Loop
while np.abs(Ratio_2I_rg) >= Tol:
    Z_i_2I_rg = Z_2I_rg - Ratio_2I_rg;
    if Z_i_2I_rg > 0:
        C_i_2I_rg = (1 - np.cos(np.sqrt(Z_i_2I_rg)))/Z_i_2I_rg;
    if Z_i_2I_rg < 0:
        C_i_2I_rg = (np.cosh(np.sqrt(-Z_i_2I_rg)) - 1)/-Z_i_2I_rg;
    if Z_i_2I_rg == 0:
        C_i_2I_rg = 0.5;
    if Z_i_2I_rg > 0:
        S_i_2I_rg = (np.sqrt(Z_i_2I_rg) - np.sin(np.sqrt(Z_i_2I_rg)))/(np.sqrt(Z_i_2I_rg)**3);
    if Z_i_2I_rg < 0:
        S_i_2I_rg = (np.sinh(np.sqrt(-Z_i_2I_rg)) - np.sqrt(-Z_i_2I_rg))/(np.sqrt(-Z_i_2I_rg)**3);
    if Z_i_2I_rg == 0:
        S_i_2I_rg = 1/6;
    y_i_2I_rg = r_initial_2IM + r_final_2IM + A_2I_rg*((Z_i_2I_rg*S_i_2I_rg - 1)/np.sqrt(C_i_2I_rg));
    if y_i_2I_rg <= 0:
        Z_2I_rg = Z_2I_rg;
        C_2I_rg = C_2I_rg;
        S_2I_rg = S_2I_rg;
        y_2I_rg = y_2I_rg;
        F_2I_rg = F_2I_rg;
        Fprime_2I_rg = Fprime_2I_rg;
        Ratio_2I_rg = Ratio_2I_rg;
        break
    if y_i_2I_rg >= 1.0E16:
        Z_2I_rg = Z_2I_rg;
        C_2I_rg = C_2I_rg;
        S_2I_rg = S_2I_rg;
        y_2I_rg = y_2I_rg;
        F_2I_rg = F_2I_rg;
        Fprime_2I_rg = Fprime_2I_rg;
        Ratio_2I_rg = Ratio_2I_rg;
        break
    F_i_2I_rg = ((y_i_2I_rg/C_i_2I_rg)**1.5)*S_i_2I_rg + A_2I_rg*np.sqrt(y_i_2I_rg) - np.sqrt(mu_S)*dt;
    if Z_i_2I_rg != 0:
        Fprime_i_2I_rg = ((y_i_2I_rg/C_i_2I_rg)**1.5)*((1/(2*Z_i_2I_rg))*(C_i_2I_rg - 1.5*(S_i_2I_rg/C_i_2I_rg)) + 0.75*((S_i_2I_rg**2)/C_i_2I_rg)) + (A_2I_rg/8)*(3*(S_i_2I_rg/C_i_2I_rg)*np.sqrt(y_i_2I_rg) + A_2I_rg*np.sqrt(C_i_2I_rg/y_i_2I_rg));
    else:
        Fprime_i_2I_rg = (np.sqrt(2)/40)*y_i_2I_rg + (A_2I_rg/8)*(np.sqrt(y_i_2I_rg) + A_2I_rg*np.sqrt(1/(2*y_i_2I_rg)));
    Ratio_2I_rg = F_i_2I_rg/Fprime_i_2I_rg;
    Z_2I_rg = Z_i_2I_rg;
    C_2I_rg = C_i_2I_rg;
    S_2I_rg = S_i_2I_rg;
    y_2I_rg = y_i_2I_rg;
    F_2I_rg = F_i_2I_rg;
    Fprime_2I_rg = Fprime_i_2I_rg;
    Ratio_2I_rg = Ratio_2I_rg;
    Iter_2I_rg += 1;
    if Iter_2I_rg >= 100:
        Z_2I_rg = Z_2I_rg;
        C_2I_rg = C_2I_rg;
        S_2I_rg = S_2I_rg;
        y_2I_rg = y_2I_rg;
        F_2I_rg = F_2I_rg;
        Fprime_2I_rg = Fprime_2I_rg;
        Ratio_2I_rg = Ratio_2I_rg;
        break
print(Ratio_2I_rg)
print(Iter_2I_rg)
print(Z_2I_rg)

-3.3290345416008358e-15
6
-14.185865397459718


In [72]:
#Retrograde E Loop
while np.abs(Ratio_E_rg) >= Tol:
    Z_i_E_rg = Z_E_rg - Ratio_E_rg;
    if Z_i_E_rg > 0:
        C_i_E_rg = (1 - np.cos(np.sqrt(Z_i_E_rg)))/Z_i_E_rg;
    if Z_i_E_rg < 0:
        C_i_E_rg = (np.cosh(np.sqrt(-Z_i_E_rg)) - 1)/-Z_i_E_rg;
    if Z_i_E_rg == 0:
        C_i_E_rg = 0.5;
    if Z_i_E_rg > 0:
        S_i_E_rg = (np.sqrt(Z_i_E_rg) - np.sin(np.sqrt(Z_i_E_rg)))/(np.sqrt(Z_i_E_rg)**3);
    if Z_i_E_rg < 0:
        S_i_E_rg = (np.sinh(np.sqrt(-Z_i_E_rg)) - np.sqrt(-Z_i_E_rg))/(np.sqrt(-Z_i_E_rg)**3);
    if Z_i_E_rg == 0:
        S_i_E_rg = 1/6;
    y_i_E_rg = r_initial_EM + r_final_EM + A_E_rg*((Z_i_E_rg*S_i_E_rg - 1)/np.sqrt(C_i_E_rg));
    if y_i_E_rg <= 0:
        Z_E_rg = Z_E_rg;
        C_E_rg = C_E_rg;
        S_E_rg = S_E_rg;
        y_E_rg = y_E_rg;
        F_E_rg = F_E_rg;
        Fprime_E_rg = Fprime_E_rg;
        Ratio_E_rg = Ratio_E_rg;
        break
    if y_i_E_rg >= 1.0E16:
        Z_E_rg = Z_E_rg;
        C_E_rg = C_E_rg;
        S_E_rg = S_E_rg;
        y_E_rg = y_E_rg;
        F_E_rg = F_E_rg;
        Fprime_E_rg = Fprime_E_rg;
        Ratio_E_rg = Ratio_E_rg;
        break
    F_i_E_rg = ((y_i_E_rg/C_i_E_rg)**1.5)*S_i_E_rg + A_E_rg*np.sqrt(y_i_E_rg) - np.sqrt(mu_S)*dt;
    if Z_i_E_rg != 0:
        Fprime_i_E_rg = ((y_i_E_rg/C_i_E_rg)**1.5)*((1/(2*Z_i_E_rg))*(C_i_E_rg - 1.5*(S_i_E_rg/C_i_E_rg)) + 0.75*((S_i_E_rg**2)/C_i_E_rg)) + (A_E_rg/8)*(3*(S_i_E_rg/C_i_E_rg)*np.sqrt(y_i_E_rg) + A_E_rg*np.sqrt(C_i_E_rg/y_i_E_rg));
    else:
        Fprime_i_E_rg = (np.sqrt(2)/40)*y_i_E_rg + (A_E_rg/8)*(np.sqrt(y_i_E_rg) + A_E_rg*np.sqrt(1/(2*y_i_E_rg)));
    Ratio_E_rg = F_i_E_rg/Fprime_i_E_rg;
    Z_E_rg = Z_i_E_rg;
    C_E_rg = C_i_E_rg;
    S_E_rg = S_i_E_rg;
    y_E_rg = y_i_E_rg;
    F_E_rg = F_i_E_rg;
    Fprime_E_rg = Fprime_i_E_rg;
    Ratio_E_rg = Ratio_E_rg;
    Iter_E_rg += 1;
    if Iter_E_rg >= 100:
        Z_E_rg = Z_E_rg;
        C_E_rg = C_E_rg;
        S_E_rg = S_E_rg;
        y_E_rg = y_E_rg;
        F_E_rg = F_E_rg;
        Fprime_E_rg = Fprime_E_rg;
        Ratio_E_rg = Ratio_E_rg;
        break
print(Ratio_E_rg)
print(Iter_E_rg)
print(Z_E_rg)

154.42652866375911
1
66.71888847989146


In [73]:
#Prograde f functions
f_1I_pg = 1 - y_1I_pg/r_initial_1IM;
f_2I_pg = 1 - y_2I_pg/r_initial_2IM;
f_E_pg = 1 - y_E_pg/r_initial_EM;
print(f_1I_pg)
print(f_2I_pg)
print(f_E_pg)

-138.69977577796155
-13.93339298991288
-0.44795938703569904


In [74]:
#Retrograde f functions
f_1I_rg = 1 - y_1I_rg/r_initial_1IM;
f_2I_rg = 1 - y_2I_rg/r_initial_2IM;
f_E_rg = 1 - y_E_rg/r_initial_EM;
print(f_1I_rg)
print(f_2I_rg)
print(f_E_rg)

-2.1894553351896393
-0.7491941232709161
-0.18785460094545803


In [75]:
#Prograde g functions
g_1I_pg = A_1I_pg*np.sqrt(y_1I_pg/mu_S);
g_2I_pg = A_2I_pg*np.sqrt(y_2I_pg/mu_S);
g_E_pg = A_E_pg*np.sqrt(y_E_pg/mu_S);
print(g_1I_pg)
print(g_2I_pg)
print(g_E_pg)

-34252.26194042375
-7354.653104364283
-69.64680322173389


In [76]:
#Retrograde g functions
g_1I_rg = A_1I_rg*np.sqrt(y_1I_rg/mu_S);
g_2I_rg = A_2I_rg*np.sqrt(y_2I_rg/mu_S);
g_E_rg = A_E_rg*np.sqrt(y_E_rg/mu_S);
print(g_1I_rg)
print(g_2I_rg)
print(g_E_rg)

264.3671019293445
185.97739852486222
63.08188159049734


In [77]:
#Prograde fdot functions
fdot_1I_pg = (np.sqrt(mu_S)/(r_initial_1IM*r_final_1IM))*np.sqrt(y_1I_pg/C_1I_pg)*(Z_1I_pg*S_1I_pg - 1);
fdot_2I_pg = (np.sqrt(mu_S)/(r_initial_2IM*r_final_2IM))*np.sqrt(y_2I_pg/C_2I_pg)*(Z_2I_pg*S_2I_pg - 1);
fdot_E_pg = (np.sqrt(mu_S)/(r_initial_EM*r_final_EM))*np.sqrt(y_E_pg/C_E_pg)*(Z_E_pg*S_E_pg - 1);
print(fdot_1I_pg)
print(fdot_2I_pg)
print(fdot_E_pg)

-0.16811779020651782
-0.023430997762943082
0.011477317735644406


In [78]:
#Retrograde fdot functions
fdot_1I_rg = (np.sqrt(mu_S)/(r_initial_1IM*r_final_1IM))*np.sqrt(y_1I_rg/C_1I_rg)*(Z_1I_rg*S_1I_rg - 1);
fdot_2I_rg = (np.sqrt(mu_S)/(r_initial_2IM*r_final_2IM))*np.sqrt(y_2I_rg/C_2I_rg)*(Z_2I_rg*S_2I_rg - 1);
fdot_E_rg = (np.sqrt(mu_S)/(r_initial_EM*r_final_EM))*np.sqrt(y_E_rg/C_E_rg)*(Z_E_rg*S_E_rg - 1);
print(fdot_1I_rg)
print(fdot_2I_rg)
print(fdot_E_rg)

-0.0040239224388025985
-0.00306376002737928
-0.015293133375529672


In [79]:
#Prograde gdot functions
gdot_1I_pg = 1 - y_1I_pg/r_final_1IM;
gdot_2I_pg = 1 - y_2I_pg/r_final_2IM;
gdot_E_pg = 1 - y_E_pg/r_final_EM;
print(gdot_1I_pg)
print(gdot_2I_pg)
print(gdot_E_pg)

-41.52432514540508
-12.43967356415357
-0.4479011177329526


In [80]:
#Retrograde gdot functions
gdot_1I_rg = 1 - y_1I_rg/r_final_1IM;
gdot_2I_rg = 1 - y_2I_rg/r_final_2IM;
gdot_E_rg = 1 - y_E_rg/r_final_EM;
print(gdot_1I_rg)
print(gdot_2I_rg)
print(gdot_E_rg)

0.029136339302933245
-0.5742301855295953
-0.18780679887312024


In [81]:
#Prograde initial velocity vectors
v_1I_pg = (1/g_1I_pg)*(r_final_1I - f_1I_pg*r_initial_1I);
v_2I_pg = (1/g_2I_pg)*(r_final_2I - f_2I_pg*r_initial_2I);
v_E_pg = (1/g_E_pg)*(r_final_E - f_E_pg*r_initial_E);
print(v_1I_pg)
print(v_2I_pg)
print(v_E_pg)

[-0.02780303 -0.00600061 -0.00950687]
[-0.00404744 -0.01308364 -0.01089975]
[ 2.23168180e-03  1.55004138e-02 -7.80883487e-07]


In [82]:
#Prograde initial velocity vector magnitudes
v_1IM_pg = np.sqrt(np.dot(v_1I_pg,v_1I_pg));
v_2IM_pg = np.sqrt(np.dot(v_2I_pg,v_2I_pg));
v_EM_pg = np.sqrt(np.dot(v_E_pg,v_E_pg));
print(v_1IM_pg)
print(v_2IM_pg)
print(v_EM_pg)

0.02998993598224141
0.017503372543065766
0.01566024373211467


In [83]:
#Retrograde initial velocity vectors
v_1I_rg = (1/g_1I_rg)*(r_final_1I - f_1I_rg*r_initial_1I);
v_2I_rg = (1/g_2I_rg)*(r_final_2I - f_2I_rg*r_initial_2I);
v_E_rg = (1/g_E_rg)*(r_final_E - f_E_rg*r_initial_E);
print(v_1I_rg)
print(v_2I_rg)
print(v_E_rg)

[0.13783287 0.02603375 0.05238196]
[ 0.00062948 -0.01750285 -0.00999597]
[-6.07471706e-03 -1.50168966e-02  9.04025859e-07]


In [84]:
#Retrograde initial velocity vector magnitudes
v_1IM_rg = np.sqrt(np.dot(v_1I_rg,v_1I_rg));
v_2IM_rg = np.sqrt(np.dot(v_2I_rg,v_2I_rg));
v_EM_rg = np.sqrt(np.dot(v_E_rg,v_E_rg));
print(v_1IM_rg)
print(v_2IM_rg)
print(v_EM_rg)

0.14973151277556773
0.020165948674013428
0.01619905460797131


In [85]:
#Prograde final velocity vectors
v_final_1I_pg = (1/g_1I_pg)*(gdot_1I_pg*r_final_1I - r_initial_1I);
v_final_2I_pg = (1/g_2I_pg)*(gdot_2I_pg*r_final_2I - r_initial_2I);
v_final_E_pg = (1/g_E_pg)*(gdot_E_pg*r_final_E - r_initial_E);
print(v_final_1I_pg)
print(v_final_2I_pg)
print(v_final_E_pg)

[0.0265623  0.00452359 0.01079252]
[-0.00234603 -0.01404131 -0.01018202]
[ 9.05117254e-03 -1.27787319e-02  2.33195414e-07]


In [86]:
#Prograde final velocity vector magnitudes
v_final_1IM_pg = np.sqrt(np.dot(v_final_1I_pg,v_final_1I_pg));
v_final_2IM_pg = np.sqrt(np.dot(v_final_2I_pg,v_final_2I_pg));
v_final_EM_pg = np.sqrt(np.dot(v_final_E_pg,v_final_E_pg));
print(v_final_1IM_pg)
print(v_final_2IM_pg)
print(v_final_EM_pg)

0.02902580344375096
0.01750245257473441
0.015659492788316912


In [87]:
#Retrograde final velocity vectors
v_final_1I_rg = (1/g_1I_rg)*(gdot_1I_rg*r_final_1I - r_initial_1I);
v_final_2I_rg = (1/g_2I_rg)*(gdot_2I_rg*r_final_2I - r_initial_2I);
v_final_E_rg = (1/g_E_rg)*(gdot_E_rg*r_final_E - r_initial_E);
print(v_final_1I_rg)
print(v_final_2I_rg)
print(v_final_E_rg)

[-0.02298145 -0.00509714 -0.00766425]
[-0.00725166 -0.0130668  -0.0133206 ]
[-1.22514012e-02  1.05966513e-02 -1.44657620e-08]


In [88]:
#Retrograde final velocity vector magnitudes
v_final_1IM_rg = np.sqrt(np.dot(v_final_1I_rg,v_final_1I_rg));
v_final_2IM_rg = np.sqrt(np.dot(v_final_2I_rg,v_final_2I_rg));
v_final_EM_rg = np.sqrt(np.dot(v_final_E_rg,v_final_E_rg));
print(v_final_1IM_rg)
print(v_final_2IM_rg)
print(v_final_EM_rg)

0.024756180483831488
0.02001914674664754
0.016198328643108495


In [89]:
#Prograde Delta Vs and Magnitudes
dv_1IE_pg = v_final_1I_pg - v_E_pg;
dv_2IE_pg = v_final_2I_pg - v_E_pg;
dv_1IEM_pg = np.sqrt(np.dot(dv_1IE_pg,dv_1IE_pg));
dv_2IEM_pg = np.sqrt(np.dot(dv_2IE_pg,dv_2IE_pg));
print(dv_1IE_pg)
print(dv_2IE_pg)
print(dv_1IEM_pg)
print(dv_2IEM_pg)

[ 0.02433062 -0.01097682  0.0107933 ]
[-0.00457771 -0.02954173 -0.01018124]
0.028791753694540203
0.03158047887534871


In [90]:
#Retrograde Delta Vs and Magnitudes
dv_1IE_rg = v_final_1I_rg - v_E_rg;
dv_2IE_rg = v_final_2I_rg - v_E_rg;
dv_1IEM_rg = np.sqrt(np.dot(dv_1IE_rg,dv_1IE_rg));
dv_2IEM_rg = np.sqrt(np.dot(dv_2IE_rg,dv_2IE_rg));
print(dv_1IE_rg)
print(dv_2IE_rg)
print(dv_1IEM_rg)
print(dv_2IEM_rg)

[-0.01690673  0.00991975 -0.00766515]
[-0.00117695  0.0019501  -0.0133215 ]
0.02104741185890839
0.013514823407863684


In [91]:
#Initial Orbital Elements
#Prograde angular momentums
h_1I_pg = np.cross(r_1I,v_1I_pg);
h_2I_pg = np.cross(r_2I,v_2I_pg);
h_E_pg = np.cross(r_E,v_E_pg);
print(h_1I_pg)
print(h_2I_pg)
print(h_E_pg)

[ 0.05702779 -0.12461209 -0.08812544]
[ 0.02709475  0.02137086 -0.03571393]
[-1.86293448e-07 -2.22130620e-07 -4.94166455e-03]


In [92]:
#Retrograde angular momentums
h_1I_rg = np.cross(r_1I,v_1I_rg);
h_2I_rg = np.cross(r_2I,v_2I_rg);
h_E_rg = np.cross(r_E,v_E_rg);
print(h_1I_rg)
print(h_2I_rg)
print(h_E_rg)

[-0.28262944  0.6175769   0.43674924]
[ 0.10324122  0.08143103 -0.13608354]
[3.23085575e-07 3.85237377e-07 8.57024521e-03]


In [93]:
#Prograde angular momentum magnitudes
h_1IM_pg = np.sqrt(np.dot(h_1I_pg,h_1I_pg));
h_2IM_pg = np.sqrt(np.dot(h_2I_pg,h_2I_pg));
h_EM_pg = np.sqrt(np.dot(h_E_pg,h_E_pg));
print(h_1IM_pg)
print(h_2IM_pg)
print(h_EM_pg)

0.1629307683129114
0.04966210149184009
0.004941664555630897


In [94]:
#Retrograde angular momentum magnitudes
h_1IM_rg = np.sqrt(np.dot(h_1I_rg,h_1I_rg));
h_2IM_rg = np.sqrt(np.dot(h_2I_rg,h_2I_rg));
h_EM_rg = np.sqrt(np.dot(h_E_rg,h_E_rg));
print(h_1IM_rg)
print(h_2IM_rg)
print(h_EM_rg)

0.8074840721378354
0.18923131923618458
0.008570245227913728


In [95]:
#Prograde inclinations
i_1I_pg = np.arccos(h_1I_pg[2]/h_1IM_pg);
i_2I_pg = np.arccos(h_2I_pg[2]/h_2IM_pg);
i_E_pg = np.arccos(h_E_pg[2]/h_EM_pg);
print(i_1I_pg)
print(i_2I_pg)
print(i_E_pg)

2.1422752865992702
2.3733581216075863
3.1415339873131813


In [96]:
#Retrograde inclinations
i_1I_rg = np.arccos(h_1I_rg[2]/h_1IM_rg);
i_2I_rg = np.arccos(h_2I_rg[2]/h_2IM_rg);
i_E_rg = np.arccos(h_E_rg[2]/h_EM_rg);
print(i_1I_rg)
print(i_2I_rg)
print(i_E_rg)

0.9993173669905229
2.373358121607586
5.8666278504200506e-05


In [97]:
#Prograde node line
K_vector = np.array([0,0,1]);
N_1I_pg = np.cross(K_vector,h_1I_pg);
N_2I_pg = np.cross(K_vector,h_2I_pg);
N_E_pg = np.cross(K_vector,h_E_pg);
print(N_1I_pg)
print(N_2I_pg)
print(N_E_pg)

[ 0.12461209  0.05702779 -0.        ]
[-0.02137086  0.02709475  0.        ]
[ 2.22130620e-07 -1.86293448e-07  0.00000000e+00]


In [98]:
#Retrograde node line
K_vector = np.array([0,0,1]);
N_1I_rg = np.cross(K_vector,h_1I_rg);
N_2I_rg = np.cross(K_vector,h_2I_rg);
N_E_rg = np.cross(K_vector,h_E_rg);
print(N_1I_rg)
print(N_2I_rg)
print(N_E_rg)

[-0.6175769  -0.28262944  0.        ]
[-0.08143103  0.10324122  0.        ]
[-3.85237377e-07  3.23085575e-07  0.00000000e+00]


In [99]:
#Prograde node line magnitudes
N_1IM_pg = np.sqrt(np.dot(N_1I_pg,N_1I_pg));
N_2IM_pg = np.sqrt(np.dot(N_2I_pg,N_2I_pg));
N_EM_pg = np.sqrt(np.dot(N_E_pg,N_E_pg));
print(N_1IM_pg)
print(N_2IM_pg)
print(N_EM_pg)

0.13704138866840032
0.03450854088040484
2.8990905715283545e-07


In [100]:
#Retrograde node line magnitudes
N_1IM_rg = np.sqrt(np.dot(N_1I_rg,N_1I_rg));
N_2IM_rg = np.sqrt(np.dot(N_2I_rg,N_2I_rg));
N_EM_rg = np.sqrt(np.dot(N_E_rg,N_E_rg));
print(N_1IM_rg)
print(N_2IM_rg)
print(N_EM_rg)

0.6791764362202087
0.1314905434839032
5.027843726790253e-07


In [101]:
#Prograde right ascensions
if N_1I_pg[1] >= 0:
    RA_1I_pg = np.arccos(N_1I_pg[0]/N_1IM_pg);
else:
    RA_1I_pg = np.pi - np.arccos(N_1I_pg[0]/N_1IM_pg);
if N_2I_pg[1] >= 0:
    RA_2I_pg = np.arccos(N_2I_pg[0]/N_2IM_pg);
else:
    RA_2I_pg = np.pi - np.arccos(N_2I_pg[0]/N_2IM_pg);
if N_E_pg[1] >= 0:
    RA_E_pg = np.arccos(N_E_pg[0]/N_EM_pg);
else:
    RA_E_pg = np.pi - np.arccos(N_E_pg[0]/N_EM_pg);
print(RA_1I_pg)
print(RA_2I_pg)
print(RA_E_pg)

0.4291912364266985
2.238636879308795
2.443715341975923


In [102]:
#Retrograde right ascensions
if N_1I_rg[1] >= 0:
    RA_1I_rg = np.arccos(N_1I_rg[0]/N_1IM_rg);
else:
    RA_1I_rg = np.pi - np.arccos(N_1I_rg[0]/N_1IM_rg);
if N_2I_rg[1] >= 0:
    RA_2I_rg = np.arccos(N_2I_rg[0]/N_2IM_rg);
else:
    RA_2I_rg = np.pi - np.arccos(N_2I_rg[0]/N_2IM_rg);
if N_E_rg[1] >= 0:
    RA_E_rg = np.arccos(N_E_rg[0]/N_EM_rg);
else:
    RA_E_rg = np.pi - np.arccos(N_E_rg[0]/N_EM_rg);
print(RA_1I_rg)
print(RA_2I_rg)
print(RA_E_rg)

0.42919123642669765
2.2386368793087943
2.4437153419759237


In [103]:
#Prograde eccentricities
e_1I_pg = (1/mu_S)*(np.cross(v_1I_pg,h_1I_pg) - mu_S*(r_1I/r_1IM));
e_2I_pg = (1/mu_S)*(np.cross(v_2I_pg,h_2I_pg) - mu_S*(r_2I/r_2IM));
e_E_pg = (1/mu_S)*(np.cross(v_E_pg,h_E_pg) - mu_S*(r_E/r_EM));
print(e_1I_pg)
print(e_2I_pg)
print(e_E_pg)

[-2.22281549 -9.53671972 12.04678627]
[ 2.03146877 -2.1612499   0.24792502]
[-7.61961839e-02 -9.45908116e-01  4.53915891e-05]


In [104]:
#Retrograde eccentricities
e_1I_rg = (1/mu_S)*(np.cross(v_1I_rg,h_1I_rg) - mu_S*(r_1I/r_1IM));
e_2I_rg = (1/mu_S)*(np.cross(v_2I_rg,h_2I_rg) - mu_S*(r_2I/r_2IM));
e_E_rg = (1/mu_S)*(np.cross(v_E_rg,h_E_rg) - mu_S*(r_E/r_EM));
print(e_1I_rg)
print(e_2I_rg)
print(e_E_rg)

[ -70.90468461 -252.88854196  311.70831936]
[10.46514146 -3.87276555  5.62206665]
[-2.52264081e-01 -8.07239988e-01  4.57958776e-05]


In [105]:
#Prograde eccentricity magnitudes
e_1IM_pg = np.sqrt(np.dot(e_1I_pg,e_1I_pg));
e_2IM_pg = np.sqrt(np.dot(e_2I_pg,e_2I_pg));
e_EM_pg = np.sqrt(np.dot(e_E_pg,e_E_pg));
print(e_1IM_pg)
print(e_2IM_pg)
print(e_EM_pg)

15.52465752014904
2.976463222617095
0.948972088538028


In [106]:
#Retrograde eccentricity magnitudes
e_1IM_rg = np.sqrt(np.dot(e_1I_rg,e_1I_rg));
e_2IM_rg = np.sqrt(np.dot(e_2I_rg,e_2I_rg));
e_EM_rg = np.sqrt(np.dot(e_E_rg,e_E_rg));
print(e_1IM_rg)
print(e_2IM_rg)
print(e_EM_rg)

407.60540393000974
12.495004292133311
0.8457384740732703


In [107]:
#Prograde arguments of perigee numerators and denominators
omega_1I_pg_n = np.dot(N_1I_pg,e_1I_pg);
omega_1I_pg_d = N_1IM_pg*e_1IM_pg;
omega_2I_pg_n = np.dot(N_2I_pg,e_2I_pg);
omega_2I_pg_d = N_2IM_pg*e_2IM_pg;
omega_E_pg_n = np.dot(N_E_pg,e_E_pg);
omega_E_pg_d = N_EM_pg*e_EM_pg;
print(omega_1I_pg_n)
print(omega_1I_pg_d)
print(omega_2I_pg_n)
print(omega_2I_pg_d)
print(omega_E_pg_n)
print(omega_E_pg_d)

-0.8208477422716662
2.1275206251625485
-0.10197277090881933
0.10271340279670355
1.5929097911145323e-07
2.751156034524168e-07


In [108]:
#Prograde arguments of perigee
if e_1I_pg[1] >= 0:
    omega_1I_pg = np.arccos(omega_1I_pg_n/omega_1I_pg_d);
else:
    omega_1I_pg = np.pi - np.arccos(omega_1I_pg_n/omega_1I_pg_d);
if e_2I_pg[1] >= 0:
    omega_2I_pg = np.arccos(omega_2I_pg_n/omega_2I_pg_d);
else:
    omega_2I_pg = np.pi - np.arccos(omega_2I_pg_n/omega_2I_pg_d);
if e_E_pg[1] >= 0:
    omega_E_pg = np.arccos(omega_E_pg_n/omega_E_pg_d);
else:
    omega_E_pg = np.pi - np.arccos(omega_E_pg_n/omega_E_pg_d);
print(omega_1I_pg)
print(omega_2I_pg)
print(omega_E_pg)

1.1746959110903465
0.12016111535413154
2.188293722823288


In [109]:
#Retrograde arguments of perigee numerators and denominators
omega_1I_rg_n = np.dot(N_1I_rg,e_1I_rg);
omega_1I_rg_d = N_1IM_rg*e_1IM_rg;
omega_2I_rg_n = np.dot(N_2I_rg,e_2I_rg);
omega_2I_rg_d = N_2IM_rg*e_2IM_rg;
omega_E_rg_n = np.dot(N_E_rg,e_E_rg);
omega_E_rg_d = N_EM_rg*e_EM_rg;
print(omega_1I_rg_n)
print(omega_1I_rg_d)
print(omega_2I_rg_n)
print(omega_2I_rg_d)
print(omega_E_rg_n)
print(omega_E_rg_d)

115.26284357272402
276.83598562528266
-1.2520163119778915
1.6429749052063125
-1.6362604283875593e-07
4.252240881374453e-07


In [110]:
#Retrograde arguments of perigee
if e_1I_rg[1] >= 0:
    omega_1I_rg = np.arccos(omega_1I_rg_n/omega_1I_rg_d);
else:
    omega_1I_rg = np.pi - np.arccos(omega_1I_rg_n/omega_1I_rg_d);
if e_2I_rg[1] >= 0:
    omega_2I_rg = np.arccos(omega_2I_rg_n/omega_2I_rg_d);
else:
    omega_2I_rg = np.pi - np.arccos(omega_2I_rg_n/omega_2I_rg_d);
if e_E_rg[1] >= 0:
    omega_E_rg = np.arccos(omega_E_rg_n/omega_E_rg_d);
else:
    omega_E_rg = np.pi - np.arccos(omega_E_rg_n/omega_E_rg_d);
print(omega_1I_rg)
print(omega_2I_rg)
print(omega_E_rg)

2.000232105377246
0.7043350996904869
1.175805673371598


In [111]:
#Prograde true anomalies numerators and denominators
theta_1I_pg_n = np.dot(e_1I_pg,r_1I);
theta_1I_pg_d = e_1IM_pg*r_1IM;
theta_2I_pg_n = np.dot(e_2I_pg,r_2I);
theta_2I_pg_d = e_2IM_pg*r_2IM;
theta_E_pg_n = np.dot(e_E_pg,r_E);
theta_E_pg_d = e_EM_pg*r_EM;
print(theta_1I_pg_n)
print(theta_1I_pg_d)
print(theta_2I_pg_n)
print(theta_2I_pg_d)
print(theta_E_pg_n)
print(theta_E_pg_d)

84.21545293159616
85.30888685807358
-13.319014569277302
64.45133258816989
-0.9008132890795655
0.9331602487013115


In [112]:
#Retrograde true anomalies numerators and denominators
theta_1I_rg_n = np.dot(e_1I_rg,r_1I);
theta_1I_rg_d = e_1IM_rg*r_1IM;
theta_2I_rg_n = np.dot(e_2I_rg,r_2I);
theta_2I_rg_d = e_2IM_rg*r_2IM;
theta_E_rg_n = np.dot(e_E_rg,r_E);
theta_E_rg_d = e_EM_rg*r_EM;
print(theta_1I_rg_n)
print(theta_1I_rg_d)
print(theta_2I_rg_n)
print(theta_2I_rg_d)
print(theta_E_rg_n)
print(theta_E_rg_d)

2197.9643086147908
2239.815161234601
99.35686337646257
270.56261646492186
-0.7351254488168874
0.8316467199981876


In [113]:
#Prograde true anomalies
if nu_r_1I >= 0:
    theta_1I_pg = np.arccos(theta_1I_pg_n/theta_1I_pg_d);
else:
    theta_1I_pg = np.pi - np.arccos(theta_1I_pg_n/theta_1I_pg_d);
if nu_r_2I >= 0:
    theta_2I_pg = np.arccos(theta_2I_pg_n/theta_2I_pg_d);
else:
    theta_2I_pg = np.pi - np.arccos(theta_2I_pg_n/theta_2I_pg_d);
if nu_r_E >= 0:
    theta_E_pg = np.arccos(theta_E_pg_n/theta_E_pg_d);
else:
    theta_E_pg = np.pi - np.arccos(theta_E_pg_n/theta_E_pg_d);
print(theta_1I_pg)
print(theta_2I_pg)
print(theta_E_pg)

2.98131273913825
1.3626441916871237
0.2640682536770158


In [114]:
#Retrograde true anomalies
if nu_r_1I >= 0:
    theta_1I_rg = np.arccos(theta_1I_rg_n/theta_1I_rg_d);
else:
    theta_1I_rg = np.pi - np.arccos(theta_1I_rg_n/theta_1I_rg_d);
if nu_r_2I >= 0:
    theta_2I_rg = np.arccos(theta_2I_rg_n/theta_2I_rg_d);
else:
    theta_2I_rg = np.pi - np.arccos(theta_2I_rg_n/theta_2I_rg_d);
if nu_r_E >= 0:
    theta_E_rg = np.arccos(theta_E_rg_n/theta_E_rg_d);
else:
    theta_E_rg = np.pi - np.arccos(theta_E_rg_n/theta_E_rg_d);
print(theta_1I_rg)
print(theta_2I_rg)
print(theta_E_rg)

2.9479773762604498
1.946818176023479
0.48657499628210843


In [115]:
#Semi-major axis
a_1I = 1/((2/r_1IM) - (nu_r_1I**2 / mu_S));
a_2I = 1/((2/r_2IM) - (nu_r_2I**2 / mu_S));
a_E = 1/((2/r_EM) - (nu_r_E**2 / mu_S));
print(a_1I)
print(a_2I)
print(a_E)

-1.304870503737988
-0.8646334514626245
0.49166915827575614
