In [1]:
#Importing all necessary modules
import numpy as np
import sympy as sym
import math
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

In [2]:
#Constants
Tol = 1.0E-8; #Tolerance
mu_S = 1.32712440042E20; #m^3/s^2
mu_day = 2.22972472E-24;
mu_S = mu_S*mu_day; #AU^3/day^2
dt_initial = 600;
dt_final = 1600;
Iter_initial_1I = 0;
Iter_initial_2I = 0;
Iter_initial_E = 0;
Iter_final_1I = 0;
Iter_final_2I = 0;
Iter_final_E = 0;
print(mu_S)
print(dt_initial)
print(dt_final)

0.00029591220821316525
600
1600


In [3]:
#Problem 1
#Initial vectors (AU and AU/day)
r_1I = np.array([3.515868886595499E-2,-3.162046390773074,4.493983111703389]);
v_1I = np.array([-2.317577766980901E-3,9.843360903693031E-3,-1.541856855538041E-2]);
r_2I = np.array([7.249472033259724,14.61063037906177,14.24274452216359]);
v_2I = np.array([-8.241709369476881E-3,-1.156219024581502E-2,-1.317135977481448E-2]);
r_E = np.array([-1.796136509111975E-1,9.667949206859814E-1,-3.668681017942158E-5]);
v_E = np.array([-1.720038360888334E-2,-3.211186197806460E-3,7.927736735960840E-7]);
print(r_1I)
print(v_1I)
print(r_2I)
print(v_2I)
print(r_E)
print(v_E)

[ 0.03515869 -3.16204639  4.49398311]
[-0.00231758  0.00984336 -0.01541857]
[ 7.24947203 14.61063038 14.24274452]
[-0.00824171 -0.01156219 -0.01317136]
[-1.79613651e-01  9.66794921e-01 -3.66868102e-05]
[-1.72003836e-02 -3.21118620e-03  7.92773674e-07]


In [4]:
#Initial Magnitudes (AU and AU/day)
r_1IM = np.sqrt(np.dot(r_1I,r_1I));
v_1IM = np.sqrt(np.dot(v_1I,v_1I));
r_2IM = np.sqrt(np.dot(r_2I,r_2I));
v_2IM = np.sqrt(np.dot(v_2I,v_2I));
r_EM = np.sqrt(np.dot(r_E,r_E));
v_EM = np.sqrt(np.dot(v_E,v_E));
print(r_1IM)
print(v_1IM)
print(r_2IM)
print(v_2IM)
print(r_EM)
print(v_EM)

5.495057571953097
0.018438958129008327
21.653663347299887
0.01936736262192
0.9833379295053073
0.017497568794498722


In [5]:
#Radial component velocities (AU/day)
nu_r_1I = (np.dot(r_1I,v_1I))/r_1IM;
nu_r_2I = (np.dot(r_2I,v_2I))/r_2IM;
nu_r_E = (np.dot(r_E,v_E))/r_EM;
print(nu_r_1I)
print(nu_r_2I)
print(nu_r_E)

-0.01828869528532203
-0.019224240962828414
-1.539128816429416e-05


In [6]:
#Alpha (Semi-major axis reciprocal, 1/AU) and Semi-major axis (AU)
alpha_1I = (2/r_1IM) - (v_1IM**2 / mu_S);
alpha_2I = (2/r_2IM) - (v_2IM**2 / mu_S);
alpha_E = (2/r_EM) - (v_EM**2 / mu_S);
print(alpha_1I)
print(alpha_2I)
print(alpha_E)

-0.785009703080843
-1.1752247768018413
0.9992410036177539


In [7]:
#Initial Universal Variable (AU^1/2)
Chi_initial_1I = np.sqrt(mu_S)*np.abs(alpha_1I)*dt_initial;
Chi_initial_2I = np.sqrt(mu_S)*np.abs(alpha_2I)*dt_initial;
Chi_initial_E = np.sqrt(mu_S)*np.abs(alpha_E)*dt_initial;
print(Chi_initial_1I)
print(Chi_initial_2I)
print(Chi_initial_E)

8.102288752472534
12.129799737937752
10.31342557021582


In [8]:
#Final Universal Variable (AU^1/2)
Chi_final_1I = np.sqrt(mu_S)*np.abs(alpha_1I)*dt_final;
Chi_final_2I = np.sqrt(mu_S)*np.abs(alpha_2I)*dt_final;
Chi_final_E = np.sqrt(mu_S)*np.abs(alpha_E)*dt_final;
print(Chi_final_1I)
print(Chi_final_2I)
print(Chi_final_E)

21.606103339926754
32.34613263450068
27.502468187242187


In [9]:
#Initial z terms
z_initial_1I = alpha_1I*Chi_initial_1I**2;
z_initial_2I = alpha_2I*Chi_initial_2I**2;
z_initial_E = alpha_E*Chi_initial_E**2;
print(z_initial_1I)
print(z_initial_2I)
print(z_initial_E)

-51.533597156281424
-172.91322084668562
106.286015016223


In [10]:
#Final z terms
z_final_1I = alpha_1I*Chi_final_1I**2;
z_final_2I = alpha_2I*Chi_final_2I**2;
z_final_E = alpha_E*Chi_final_E**2;
print(z_final_1I)
print(z_final_2I)
print(z_final_E)

-366.46113533355674
-1229.6051260208758
755.8116623375859


In [11]:
#Initial C functions
C_initial_1I = (np.cosh(np.sqrt(-z_initial_1I)) - 1)/-z_initial_1I;
C_initial_2I = (np.cosh(np.sqrt(-z_initial_2I)) - 1)/-z_initial_2I;
C_initial_E = (1 - np.cos(np.sqrt(z_initial_E)))/z_initial_E;
print(C_initial_1I)
print(C_initial_2I)
print(C_initial_E)

12.70230444148628
1485.7964654091058
0.015368872003262271


In [12]:
#Final C functions
C_final_1I = (np.cosh(np.sqrt(-z_final_1I)) - 1)/-z_final_1I;
C_final_2I = (np.cosh(np.sqrt(-z_final_2I)) - 1)/-z_final_2I;
C_final_E = (1 - np.cos(np.sqrt(z_final_E)))/z_final_E;
print(C_final_1I)
print(C_final_2I)
print(C_final_E)

281007.0333484178
688740400927.8279
0.0022615299666585583


In [13]:
#Initial S functions
S_initial_1I = (np.sinh(np.sqrt(-z_initial_1I)) - np.sqrt(-z_initial_1I))/(np.sqrt(-z_initial_1I)**3);
S_initial_2I = (np.sinh(np.sqrt(-z_initial_2I)) - np.sqrt(-z_initial_2I))/(np.sqrt(-z_initial_2I)**3);
S_initial_E = (np.sqrt(z_initial_E) - np.sin(np.sqrt(z_initial_E)))/(np.sqrt(z_initial_E)**3);
print(S_initial_1I)
print(S_initial_2I)
print(S_initial_E)

1.7527421335961526
112.98601256145113
0.01011470467398887


In [14]:
#Final S functions
S_final_1I = (np.sinh(np.sqrt(-z_final_1I)) - np.sqrt(-z_final_1I))/(np.sqrt(-z_final_1I)**3);
S_final_2I = (np.sinh(np.sqrt(-z_final_2I)) - np.sqrt(-z_final_2I))/(np.sqrt(-z_final_2I)**3);
S_final_E = (np.sqrt(z_final_E) - np.sin(np.sqrt(z_final_E)))/(np.sqrt(z_final_E)**3);
print(S_final_1I)
print(S_final_2I)
print(S_final_E)

14679.225839495928
19641412951.691013
0.001289156154631272


In [15]:
#f initial (AU^1/2)
f_initial_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*(Chi_initial_1I**2)*(C_initial_1I) + (1 - alpha_1I*r_1IM)*(Chi_initial_1I**3)*(S_initial_1I) + (r_1IM*Chi_initial_1I) - np.sqrt(mu_S)*dt_initial;
f_initial_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*(Chi_initial_2I**2)*(C_initial_2I) + (1 - alpha_2I*r_2IM)*(Chi_initial_2I**3)*(S_initial_2I) + (r_2IM*Chi_initial_2I) - np.sqrt(mu_S)*dt_initial;
f_initial_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*(Chi_initial_E**2)*(C_initial_E) + (1 - alpha_E*r_EM)*(Chi_initial_E**3)*(S_initial_E) + (r_EM*Chi_initial_E) - np.sqrt(mu_S)*dt_initial;
print(f_initial_1I)
print(f_initial_2I)
print(f_initial_E)

116.37520436850168
43197.94501610339
0.01204676002369176


In [16]:
#f final (AU^1/2)
f_final_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*(Chi_final_1I**2)*(C_final_1I) + (1 - alpha_1I*r_1IM)*(Chi_final_1I**3)*(S_final_1I) + (r_1IM*Chi_final_1I) - np.sqrt(mu_S)*dt_final;
f_final_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*(Chi_final_2I**2)*(C_final_2I) + (1 - alpha_2I*r_2IM)*(Chi_final_2I**3)*(S_final_2I) + (r_2IM*Chi_final_2I) - np.sqrt(mu_S)*dt_final;
f_final_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*(Chi_final_E**2)*(C_final_E) + (1 - alpha_E*r_EM)*(Chi_final_E**3)*(S_final_E) + (r_EM*Chi_final_E) - np.sqrt(mu_S)*dt_final;
print(f_final_1I)
print(f_final_2I)
print(f_final_E)

20354050.09231681
142395287789182.88
-0.013790478720107302


In [17]:
#fprime initial (AU^2/3)
fprime_initial_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*Chi_initial_1I*(1 - alpha_1I*(Chi_initial_1I**2)*S_initial_1I) + (1 - alpha_1I*r_1IM)*(Chi_initial_1I**2)*C_initial_1I + r_1IM;
fprime_initial_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*Chi_initial_2I*(1 - alpha_2I*(Chi_initial_2I**2)*S_initial_2I) + (1 - alpha_2I*r_2IM)*(Chi_initial_2I**2)*C_initial_2I + r_2IM;
fprime_initial_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*Chi_initial_E*(1 - alpha_E*(Chi_initial_E**2)*S_initial_E) + (1 - alpha_E*r_EM)*(Chi_initial_E**2)*C_initial_E + r_EM;
print(fprime_initial_1I)
print(fprime_initial_2I)
print(fprime_initial_E)

113.54128018761274
46829.14019421005
1.0124771365481888


In [18]:
#fprime final (AU^2/3)
fprime_final_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*Chi_final_1I*(1 - alpha_1I*(Chi_final_1I**2)*S_final_1I) + (1 - alpha_1I*r_1IM)*(Chi_final_1I**2)*C_final_1I + r_1IM;
fprime_final_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*Chi_final_2I*(1 - alpha_2I*(Chi_final_2I**2)*S_final_2I) + (1 - alpha_2I*r_2IM)*(Chi_final_2I**2)*C_final_2I + r_2IM;
fprime_final_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*Chi_final_E*(1 - alpha_E*(Chi_final_E**2)*S_final_E) + (1 - alpha_E*r_EM)*(Chi_final_E**2)*C_final_E + r_EM;
print(fprime_final_1I)
print(fprime_final_2I)
print(fprime_final_E)

18033886.685471404
154367576907401.66
1.0124961446270202


In [19]:
#Ratio initial
Ratio_initial_1I = f_initial_1I/fprime_initial_1I;
Ratio_initial_2I = f_initial_2I/fprime_initial_2I;
Ratio_initial_E = f_initial_E/fprime_initial_E;
print(Ratio_initial_1I)
print(Ratio_initial_2I)
print(Ratio_initial_E)

1.0249594171935197
0.9224586408580779
0.011898303269111296


In [20]:
#Ratio final
Ratio_final_1I = f_final_1I/fprime_final_1I;
Ratio_final_2I = f_final_2I/fprime_final_2I;
Ratio_final_E = f_final_E/fprime_final_E;
print(Ratio_final_1I)
print(Ratio_final_2I)
print(Ratio_final_E)

1.1286557605307896
0.922442980850827
-0.013620277759366077


In [21]:
#1I Initial Loop
while np.abs(Ratio_initial_1I) >= Tol:
    Chi_i_initial_1I = Chi_initial_1I - Ratio_initial_1I;
    z_initial_1I = alpha_1I*Chi_i_initial_1I**2;
    C_initial_1I = (np.cosh(np.sqrt(-z_initial_1I)) - 1)/-z_initial_1I;
    S_initial_1I = (np.sinh(np.sqrt(-z_initial_1I)) - np.sqrt(-z_initial_1I))/(np.sqrt(-z_initial_1I)**3);
    f_initial_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*(Chi_i_initial_1I**2)*(C_initial_1I) + (1 - alpha_1I*r_1IM)*(Chi_i_initial_1I**3)*(S_initial_1I) + (r_1IM*Chi_i_initial_1I) - np.sqrt(mu_S)*dt_initial;
    fprime_initial_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*Chi_i_initial_1I*(1 - alpha_1I*(Chi_i_initial_1I**2)*S_initial_1I) + (1 - alpha_1I*r_1IM)*(Chi_i_initial_1I**2)*C_initial_1I + r_1IM;
    Ratio_initial_1I = f_initial_1I/fprime_initial_1I;
    Chi_initial_1I = Chi_i_initial_1I;
    Iter_initial_1I += 1;
print(Ratio_initial_1I)
print(Iter_initial_1I)
print(Chi_initial_1I)

1.6962750155884766e-12
7
5.156119158905382


In [22]:
#1I Final Loop
while np.abs(Ratio_final_1I) >= Tol:
    Chi_i_final_1I = Chi_final_1I - Ratio_final_1I;
    z_final_1I = alpha_1I*Chi_i_final_1I**2;
    C_final_1I = (np.cosh(np.sqrt(-z_final_1I)) - 1)/-z_final_1I;
    S_final_1I = (np.sinh(np.sqrt(-z_final_1I)) - np.sqrt(-z_final_1I))/(np.sqrt(-z_final_1I)**3);
    f_final_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*(Chi_i_final_1I**2)*(C_final_1I) + (1 - alpha_1I*r_1IM)*(Chi_i_final_1I**3)*(S_final_1I) + (r_1IM*Chi_i_final_1I) - np.sqrt(mu_S)*dt_final;
    fprime_final_1I = ((r_1IM*nu_r_1I)/np.sqrt(mu_S))*Chi_i_final_1I*(1 - alpha_1I*(Chi_i_final_1I**2)*S_final_1I) + (1 - alpha_1I*r_1IM)*(Chi_i_final_1I**2)*C_final_1I + r_1IM;
    Ratio_final_1I = f_final_1I/fprime_final_1I;
    Chi_final_1I = Chi_i_final_1I;
    Iter_final_1I += 1;
print(Ratio_final_1I)
print(Iter_final_1I)
print(Chi_final_1I)

4.4093523592594005e-14
18
6.382629131986297


In [23]:
#2I Initial Loop
while np.abs(Ratio_initial_2I) >= Tol:
    Chi_i_initial_2I = Chi_initial_2I - Ratio_initial_2I;
    z_initial_2I = alpha_2I*Chi_i_initial_2I**2;
    C_initial_2I = (np.cosh(np.sqrt(-z_initial_2I)) - 1)/-z_initial_2I;
    S_initial_2I = (np.sinh(np.sqrt(-z_initial_2I)) - np.sqrt(-z_initial_2I))/(np.sqrt(-z_initial_2I)**3);
    f_initial_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*(Chi_i_initial_2I**2)*(C_initial_2I) + (1 - alpha_2I*r_2IM)*(Chi_i_initial_2I**3)*(S_initial_2I) + (r_2IM*Chi_i_initial_2I) - np.sqrt(mu_S)*dt_initial;
    fprime_initial_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*Chi_i_initial_2I*(1 - alpha_2I*(Chi_i_initial_2I**2)*S_initial_2I) + (1 - alpha_2I*r_2IM)*(Chi_i_initial_2I**2)*C_initial_2I + r_2IM;
    Ratio_initial_2I = f_initial_2I/fprime_initial_2I;
    Chi_initial_2I = Chi_i_initial_2I;
    Iter_initial_2I += 1;
print(Ratio_initial_2I)
print(Iter_initial_2I)
print(Chi_initial_2I)

-3.310283330448534e-14
16
0.6825310102435472


In [24]:
#2I Final Loop
while np.abs(Ratio_final_2I) >= Tol:
    Chi_i_final_2I = Chi_final_2I - Ratio_final_2I;
    z_final_2I = alpha_2I*Chi_i_final_2I**2;
    C_final_2I = (np.cosh(np.sqrt(-z_final_2I)) - 1)/-z_final_2I;
    S_final_2I = (np.sinh(np.sqrt(-z_final_2I)) - np.sqrt(-z_final_2I))/(np.sqrt(-z_final_2I)**3);
    f_final_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*(Chi_i_final_2I**2)*(C_final_2I) + (1 - alpha_2I*r_2IM)*(Chi_i_final_2I**3)*(S_final_2I) + (r_2IM*Chi_i_final_2I) - np.sqrt(mu_S)*dt_final;
    fprime_final_2I = ((r_2IM*nu_r_2I)/np.sqrt(mu_S))*Chi_i_final_2I*(1 - alpha_2I*(Chi_i_final_2I**2)*S_final_2I) + (1 - alpha_2I*r_2IM)*(Chi_i_final_2I**2)*C_final_2I + r_2IM;
    Ratio_final_2I = f_final_2I/fprime_final_2I;
    Chi_final_2I = Chi_i_final_2I;
    Iter_final_2I += 1;
print(Ratio_final_2I)
print(Iter_final_2I)
print(Chi_final_2I)

6.7074295283888946e-09
34
4.48847658912458


In [25]:
#E Initial Loop
while np.abs(Ratio_initial_E) >= Tol:
    Chi_i_initial_E = Chi_initial_E - Ratio_initial_E;
    z_initial_E = alpha_E*Chi_i_initial_E**2;
    C_initial_E = (1 - np.cos(np.sqrt(z_initial_E)))/z_initial_E;
    S_initial_E = (np.sqrt(z_initial_E) - np.sin(np.sqrt(z_initial_E)))/(np.sqrt(z_initial_E)**3);
    f_initial_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*(Chi_i_initial_E**2)*(C_initial_E) + (1 - alpha_E*r_EM)*(Chi_i_initial_E**3)*(S_initial_E) + (r_EM*Chi_i_initial_E) - np.sqrt(mu_S)*dt_initial;
    fprime_initial_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*Chi_i_initial_E*(1 - alpha_E*(Chi_i_initial_E**2)*S_initial_E) + (1 - alpha_E*r_EM)*(Chi_i_initial_E**2)*C_initial_E + r_EM;
    Ratio_initial_E = f_initial_E/fprime_initial_E;
    Chi_initial_E = Chi_i_initial_E;
    Iter_initial_E += 1;
print(Ratio_initial_E)
print(Iter_initial_E)
print(Chi_initial_E)

-5.262603892710835e-15
2
10.301528166644339


In [26]:
#E Final Loop
while np.abs(Ratio_final_E) >= Tol:
    Chi_i_final_E = Chi_final_E - Ratio_final_E;
    z_final_E = alpha_E*Chi_i_final_E**2;
    C_final_E = (1 - np.cos(np.sqrt(z_final_E)))/z_final_E;
    S_final_E = (np.sqrt(z_final_E) - np.sin(np.sqrt(z_final_E)))/(np.sqrt(z_final_E)**3);
    f_final_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*(Chi_i_final_E**2)*(C_final_E) + (1 - alpha_E*r_EM)*(Chi_i_final_E**3)*(S_final_E) + (r_EM*Chi_i_final_E) - np.sqrt(mu_S)*dt_final;
    fprime_final_E = ((r_EM*nu_r_E)/np.sqrt(mu_S))*Chi_i_final_E*(1 - alpha_E*(Chi_i_final_E**2)*S_final_E) + (1 - alpha_E*r_EM)*(Chi_i_final_E**2)*C_final_E + r_EM;
    Ratio_final_E = f_final_E/fprime_final_E;
    Chi_final_E = Chi_i_final_E;
    Iter_final_E += 1;
print(Ratio_final_E)
print(Iter_final_E)
print(Chi_final_E)

1.0524784226222152e-14
2
27.51608728829896


In [27]:
#Initial f functions
f_func_initial_1I = 1 - ((Chi_initial_1I**2)/r_1IM)*C_initial_1I;
f_func_initial_2I = 1 - ((Chi_initial_2I**2)/r_2IM)*C_initial_2I;
f_func_initial_E = 1 - ((Chi_initial_E**2)/r_EM)*C_initial_E;
print(f_func_initial_1I)
print(f_func_initial_2I)
print(f_func_initial_E)

-9.941535256802489
0.9887433898238898
-0.6717558438930185


In [28]:
#Final f functions
f_func_final_1I = 1 - ((Chi_final_1I**2)/r_1IM)*C_final_1I;
f_func_final_2I = 1 - ((Chi_final_2I**2)/r_2IM)*C_final_2I;
f_func_final_E = 1 - ((Chi_final_E**2)/r_EM)*C_final_E;
print(f_func_final_1I)
print(f_func_final_2I)
print(f_func_final_E)

-31.888067816866688
-1.5108131669967277
-0.7492734656019839


In [29]:
#Initial g functions
g_func_initial_1I = dt_initial - (1/np.sqrt(mu_S))*(Chi_initial_1I**3)*S_initial_1I;
g_func_initial_2I = dt_initial - (1/np.sqrt(mu_S))*(Chi_initial_2I**3)*S_initial_2I;
g_func_initial_E = dt_initial - (1/np.sqrt(mu_S))*(Chi_initial_E**3)*S_initial_E;
print(g_func_initial_1I)
print(g_func_initial_2I)
print(g_func_initial_E)

-3045.746351144728
596.8339706383401
-43.897192381605464


In [30]:
#Final g functions
g_func_final_1I = dt_final - (1/np.sqrt(mu_S))*(Chi_final_1I**3)*S_final_1I;
g_func_final_2I = dt_final - (1/np.sqrt(mu_S))*(Chi_final_2I**3)*S_final_2I;
g_func_final_E = dt_final - (1/np.sqrt(mu_S))*(Chi_final_E**3)*S_final_E;
print(g_func_final_1I)
print(g_func_final_2I)
print(g_func_final_E)

-9868.093966419072
-1138.6931114916033
39.66711246519503


In [31]:
#Initial position vectors
r_initial_1I = f_func_initial_1I*r_1I + g_func_initial_1I*v_1I;
r_initial_2I = f_func_initial_2I*r_2I + g_func_initial_2I*v_2I;
r_initial_E = f_func_initial_E*r_E + g_func_initial_E*v_E;
print(r_initial_1I)
print(r_initial_2I)
print(r_initial_E)

[6.70922268 1.45521512 2.28395737]
[2.24893542 7.54545629 6.22130455]
[ 8.75705068e-01 -5.08488080e-01 -1.01559593e-05]


In [32]:
#Final position vectors
r_final_1I = f_func_final_1I*r_1I + g_func_final_1I*v_1I;
r_final_2I = f_func_final_2I*r_2I + g_func_final_2I*v_2I;
r_final_E = f_func_final_E*r_E + g_func_final_E*v_E;
print(r_final_1I)
print(r_final_2I)
print(r_final_E)

[21.74893252  3.69633941  8.8474451 ]
[-1.56782012 -8.90814637 -6.51998931]
[-5.47709808e-01 -8.51772265e-01  5.89354959e-05]


In [33]:
#Initial position vector magnitudes
r_initial_1IM = np.sqrt(np.dot(r_initial_1I,r_initial_1I));
r_initial_2IM = np.sqrt(np.dot(r_initial_2I,r_initial_2I));
r_initial_EM = np.sqrt(np.dot(r_initial_E,r_initial_E));
print(r_initial_1IM)
print(r_initial_2IM)
print(r_initial_EM)

7.235176660999482
10.0347521891072
1.0126299882805065


In [34]:
#Final position vector magnitudes
r_final_1IM = np.sqrt(np.dot(r_final_1I,r_final_1I));
r_final_2IM = np.sqrt(np.dot(r_final_2I,r_final_2I));
r_final_EM = np.sqrt(np.dot(r_final_E,r_final_E));
print(r_final_1IM)
print(r_final_2IM)
print(r_final_EM)

23.7688088829032
11.150040012580032
1.0126707405408886


In [35]:
#Initial fdot functions
fdot_initial_1I = (np.sqrt(mu_S)/(r_1IM*r_initial_1IM))*(alpha_1I*(Chi_initial_1I**3)*S_initial_1I - Chi_initial_1I);
fdot_initial_2I = (np.sqrt(mu_S)/(r_2IM*r_initial_2IM))*(alpha_2I*(Chi_initial_2I**3)*S_initial_2I - Chi_initial_2I);
fdot_initial_E = (np.sqrt(mu_S)/(r_EM*r_initial_EM))*(alpha_E*(Chi_initial_E**3)*S_initial_E - Chi_initial_E);
print(fdot_initial_1I)
print(fdot_initial_2I)
print(fdot_initial_E)

-0.023532060969045778
-5.91009502028427e-05
0.013240690244398532


In [36]:
#Final fdot functions
fdot_final_1I = (np.sqrt(mu_S)/(r_1IM*r_final_1IM))*(alpha_1I*(Chi_final_1I**3)*S_final_1I - Chi_final_1I);
fdot_final_2I = (np.sqrt(mu_S)/(r_2IM*r_final_2IM))*(alpha_2I*(Chi_final_2I**3)*S_final_2I - Chi_final_2I);
fdot_final_E = (np.sqrt(mu_S)/(r_EM*r_final_EM))*(alpha_E*(Chi_final_E**3)*S_final_E - Chi_final_E);
print(fdot_final_1I)
print(fdot_final_2I)
print(fdot_final_E)

-0.021236833703424135
-0.004264544777268291
-0.01201383844455548


In [37]:
#Initial gdot functions
gdot_initial_1I = 1 - ((Chi_initial_1I**2)/r_initial_1IM)*C_initial_1I;
gdot_initial_2I = 1 - ((Chi_initial_2I**2)/r_initial_2IM)*C_initial_2I;
gdot_initial_E = 1 - ((Chi_initial_E**2)/r_initial_EM)*C_initial_E;
print(gdot_initial_1I)
print(gdot_initial_2I)
print(gdot_initial_E)

-7.3100066492887255
0.9757097292895911
-0.6233974395362116


In [38]:
#Final gdot functions
gdot_final_1I = 1 - ((Chi_final_1I**2)/r_final_1IM)*C_final_1I;
gdot_final_2I = 1 - ((Chi_final_2I**2)/r_final_2IM)*C_final_2I;
gdot_final_E = 1 - ((Chi_final_E**2)/r_final_EM)*C_final_E;
print(gdot_final_1I)
print(gdot_final_2I)
print(gdot_final_E)

-6.603318574956974
-3.876063492577064
-0.6986043725178361


In [39]:
#Initial velocity vectors
v_initial_1I = fdot_initial_1I*r_1I + gdot_initial_1I*v_1I;
v_initial_2I = fdot_initial_2I*r_2I + gdot_initial_2I*v_2I;
v_initial_E = fdot_initial_E*r_E + gdot_initial_E*v_E;
print(v_initial_1I)
print(v_initial_2I)
print(v_initial_E)

[0.01611415 0.00245443 0.00695715]
[-0.00846997 -0.01214484 -0.01369318]
[ 8.34446639e-03  1.48028773e-02 -9.79971768e-07]


In [40]:
#Final velocity vectors
v_final_1I = fdot_final_1I*r_1I + gdot_final_1I*v_1I;
v_final_2I = fdot_final_2I*r_2I + gdot_final_2I*v_2I;
v_final_E = fdot_final_E*r_E + gdot_final_E*v_E;
print(v_final_1I)
print(v_final_2I)
print(v_final_E)

[0.01455705 0.00215301 0.00637575]
[ 0.00102969 -0.0174919  -0.00968579]
[ 1.41741126e-02 -9.37156927e-03 -1.13085744e-07]


In [41]:
#Initial velocity vector magnitudes
v_initial_1IM = np.sqrt(np.dot(v_initial_1I,v_initial_1I));
v_initial_2IM = np.sqrt(np.dot(v_initial_2I,v_initial_2I));
v_initial_EM = np.sqrt(np.dot(v_initial_E,v_initial_E));
print(v_initial_1IM)
print(v_initial_2IM)
print(v_initial_EM)

0.017722645208019597
0.020167816957524155
0.016992801340955817


In [42]:
#Final velocity vector magnitudes
v_final_1IM = np.sqrt(np.dot(v_final_1I,v_final_1I));
v_final_2IM = np.sqrt(np.dot(v_final_2I,v_final_2I));
v_final_EM = np.sqrt(np.dot(v_final_E,v_final_E));
print(v_final_1IM)
print(v_final_2IM)
print(v_final_EM)

0.01603724285861022
0.020021028747810588
0.016992109287881328
